// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googleconnectoroauth2.proxies;

public class GoogleOAuthSettings
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject googleOAuthSettingsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GoogleConnectorOAuth2.GoogleOAuthSettings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OAuthName("OAuthName"),
		ClientID("ClientID"),
		ClientSecret("ClientSecret"),
		RedirectURI("RedirectURI"),
		Scope("Scope"),
		Code("Code"),
		Active("Active"),
		AccessToken("AccessToken"),
		RefreshToken("RefreshToken"),
		Token_type("Token_type"),
		TokenExpiresIn("TokenExpiresIn");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GoogleOAuthSettings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected GoogleOAuthSettings(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject googleOAuthSettingsMendixObject)
	{
		if (googleOAuthSettingsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, googleOAuthSettingsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.googleOAuthSettingsMendixObject = googleOAuthSettingsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GoogleOAuthSettings.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static googleconnectoroauth2.proxies.GoogleOAuthSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return googleconnectoroauth2.proxies.GoogleOAuthSettings.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static googleconnectoroauth2.proxies.GoogleOAuthSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new googleconnectoroauth2.proxies.GoogleOAuthSettings(context, mendixObject);
	}

	public static googleconnectoroauth2.proxies.GoogleOAuthSettings load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return googleconnectoroauth2.proxies.GoogleOAuthSettings.initialize(context, mendixObject);
	}

	public static java.util.List<googleconnectoroauth2.proxies.GoogleOAuthSettings> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> googleconnectoroauth2.proxies.GoogleOAuthSettings.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of OAuthName
	 */
	public final java.lang.String getOAuthName()
	{
		return getOAuthName(getContext());
	}

	/**
	 * @param context
	 * @return value of OAuthName
	 */
	public final java.lang.String getOAuthName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OAuthName.toString());
	}

	/**
	 * Set value of OAuthName
	 * @param oauthname
	 */
	public final void setOAuthName(java.lang.String oauthname)
	{
		setOAuthName(getContext(), oauthname);
	}

	/**
	 * Set value of OAuthName
	 * @param context
	 * @param oauthname
	 */
	public final void setOAuthName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String oauthname)
	{
		getMendixObject().setValue(context, MemberNames.OAuthName.toString(), oauthname);
	}

	/**
	 * @return value of ClientID
	 */
	public final java.lang.String getClientID()
	{
		return getClientID(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientID
	 */
	public final java.lang.String getClientID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientID.toString());
	}

	/**
	 * Set value of ClientID
	 * @param clientid
	 */
	public final void setClientID(java.lang.String clientid)
	{
		setClientID(getContext(), clientid);
	}

	/**
	 * Set value of ClientID
	 * @param context
	 * @param clientid
	 */
	public final void setClientID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientid)
	{
		getMendixObject().setValue(context, MemberNames.ClientID.toString(), clientid);
	}

	/**
	 * @return value of ClientSecret
	 */
	public final java.lang.String getClientSecret()
	{
		return getClientSecret(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientSecret
	 */
	public final java.lang.String getClientSecret(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientSecret.toString());
	}

	/**
	 * Set value of ClientSecret
	 * @param clientsecret
	 */
	public final void setClientSecret(java.lang.String clientsecret)
	{
		setClientSecret(getContext(), clientsecret);
	}

	/**
	 * Set value of ClientSecret
	 * @param context
	 * @param clientsecret
	 */
	public final void setClientSecret(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientsecret)
	{
		getMendixObject().setValue(context, MemberNames.ClientSecret.toString(), clientsecret);
	}

	/**
	 * @return value of RedirectURI
	 */
	public final java.lang.String getRedirectURI()
	{
		return getRedirectURI(getContext());
	}

	/**
	 * @param context
	 * @return value of RedirectURI
	 */
	public final java.lang.String getRedirectURI(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RedirectURI.toString());
	}

	/**
	 * Set value of RedirectURI
	 * @param redirecturi
	 */
	public final void setRedirectURI(java.lang.String redirecturi)
	{
		setRedirectURI(getContext(), redirecturi);
	}

	/**
	 * Set value of RedirectURI
	 * @param context
	 * @param redirecturi
	 */
	public final void setRedirectURI(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String redirecturi)
	{
		getMendixObject().setValue(context, MemberNames.RedirectURI.toString(), redirecturi);
	}

	/**
	 * @return value of Scope
	 */
	public final java.lang.String getScope()
	{
		return getScope(getContext());
	}

	/**
	 * @param context
	 * @return value of Scope
	 */
	public final java.lang.String getScope(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Scope.toString());
	}

	/**
	 * Set value of Scope
	 * @param scope
	 */
	public final void setScope(java.lang.String scope)
	{
		setScope(getContext(), scope);
	}

	/**
	 * Set value of Scope
	 * @param context
	 * @param scope
	 */
	public final void setScope(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String scope)
	{
		getMendixObject().setValue(context, MemberNames.Scope.toString(), scope);
	}

	/**
	 * @return value of Code
	 */
	public final java.lang.String getCode()
	{
		return getCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Code
	 */
	public final java.lang.String getCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Code.toString());
	}

	/**
	 * Set value of Code
	 * @param code
	 */
	public final void setCode(java.lang.String code)
	{
		setCode(getContext(), code);
	}

	/**
	 * Set value of Code
	 * @param context
	 * @param code
	 */
	public final void setCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String code)
	{
		getMendixObject().setValue(context, MemberNames.Code.toString(), code);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @return value of AccessToken
	 */
	public final java.lang.String getAccessToken()
	{
		return getAccessToken(getContext());
	}

	/**
	 * @param context
	 * @return value of AccessToken
	 */
	public final java.lang.String getAccessToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AccessToken.toString());
	}

	/**
	 * Set value of AccessToken
	 * @param accesstoken
	 */
	public final void setAccessToken(java.lang.String accesstoken)
	{
		setAccessToken(getContext(), accesstoken);
	}

	/**
	 * Set value of AccessToken
	 * @param context
	 * @param accesstoken
	 */
	public final void setAccessToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accesstoken)
	{
		getMendixObject().setValue(context, MemberNames.AccessToken.toString(), accesstoken);
	}

	/**
	 * @return value of RefreshToken
	 */
	public final java.lang.String getRefreshToken()
	{
		return getRefreshToken(getContext());
	}

	/**
	 * @param context
	 * @return value of RefreshToken
	 */
	public final java.lang.String getRefreshToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RefreshToken.toString());
	}

	/**
	 * Set value of RefreshToken
	 * @param refreshtoken
	 */
	public final void setRefreshToken(java.lang.String refreshtoken)
	{
		setRefreshToken(getContext(), refreshtoken);
	}

	/**
	 * Set value of RefreshToken
	 * @param context
	 * @param refreshtoken
	 */
	public final void setRefreshToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refreshtoken)
	{
		getMendixObject().setValue(context, MemberNames.RefreshToken.toString(), refreshtoken);
	}

	/**
	 * @return value of Token_type
	 */
	public final java.lang.String getToken_type()
	{
		return getToken_type(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_type
	 */
	public final java.lang.String getToken_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token_type.toString());
	}

	/**
	 * Set value of Token_type
	 * @param token_type
	 */
	public final void setToken_type(java.lang.String token_type)
	{
		setToken_type(getContext(), token_type);
	}

	/**
	 * Set value of Token_type
	 * @param context
	 * @param token_type
	 */
	public final void setToken_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token_type)
	{
		getMendixObject().setValue(context, MemberNames.Token_type.toString(), token_type);
	}

	/**
	 * @return value of TokenExpiresIn
	 */
	public final java.util.Date getTokenExpiresIn()
	{
		return getTokenExpiresIn(getContext());
	}

	/**
	 * @param context
	 * @return value of TokenExpiresIn
	 */
	public final java.util.Date getTokenExpiresIn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TokenExpiresIn.toString());
	}

	/**
	 * Set value of TokenExpiresIn
	 * @param tokenexpiresin
	 */
	public final void setTokenExpiresIn(java.util.Date tokenexpiresin)
	{
		setTokenExpiresIn(getContext(), tokenexpiresin);
	}

	/**
	 * Set value of TokenExpiresIn
	 * @param context
	 * @param tokenexpiresin
	 */
	public final void setTokenExpiresIn(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date tokenexpiresin)
	{
		getMendixObject().setValue(context, MemberNames.TokenExpiresIn.toString(), tokenexpiresin);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return googleOAuthSettingsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final googleconnectoroauth2.proxies.GoogleOAuthSettings that = (googleconnectoroauth2.proxies.GoogleOAuthSettings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
