// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googleconnectoroauth2.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the GoogleConnectorOAuth2 module
	public static void aCT_GoogleOAuthSettings_ToogleActive(IContext context, googleconnectoroauth2.proxies.GoogleOAuthSettings _googleOAuthSettings)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleOAuthSettings", _googleOAuthSettings == null ? null : _googleOAuthSettings.getMendixObject());
		Core.microflowCall("GoogleConnectorOAuth2.ACT_GoogleOAuthSettings_ToogleActive").withParams(params).execute(context);
	}
	public static java.lang.String aCT_OAuthSettings_Auth(IContext context, googleconnectoroauth2.proxies.GoogleOAuthSettings _googleOAuthSettings)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleOAuthSettings", _googleOAuthSettings == null ? null : _googleOAuthSettings.getMendixObject());
		return (java.lang.String) Core.microflowCall("GoogleConnectorOAuth2.ACT_OAuthSettings_Auth").withParams(params).execute(context);
	}
	public static void aCT_OAuthSettings_Save(IContext context, googleconnectoroauth2.proxies.GoogleOAuthSettings _googleOAuthSettings)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleOAuthSettings", _googleOAuthSettings == null ? null : _googleOAuthSettings.getMendixObject());
		Core.microflowCall("GoogleConnectorOAuth2.ACT_OAuthSettings_Save").withParams(params).execute(context);
	}
	public static void aCT_RefreshToken(IContext context, googleconnectoroauth2.proxies.GoogleOAuthSettings _googleOAuthSettings)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleOAuthSettings", _googleOAuthSettings == null ? null : _googleOAuthSettings.getMendixObject());
		Core.microflowCall("GoogleConnectorOAuth2.ACT_RefreshToken").withParams(params).execute(context);
	}
	public static void aCT_RevokeAccess(IContext context, googleconnectoroauth2.proxies.GoogleOAuthSettings _googleOAuthSettings)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleOAuthSettings", _googleOAuthSettings == null ? null : _googleOAuthSettings.getMendixObject());
		Core.microflowCall("GoogleConnectorOAuth2.ACT_RevokeAccess").withParams(params).execute(context);
	}
	public static void googleCallback(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse, java.lang.String _code, java.lang.String _state)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		params.put("code", _code);
		params.put("state", _state);
		Core.microflowCall("GoogleConnectorOAuth2.GoogleCallback").withParams(params).execute(context);
	}
	public static void sCE_RefreshToken(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("GoogleConnectorOAuth2.SCE_RefreshToken").withParams(params).execute(context);
	}
	public static googleconnectoroauth2.proxies.TokenResponse sUB_GenerateToken(IContext context, googleconnectoroauth2.proxies.GoogleOAuthSettings _googleOAuthSettings)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleOAuthSettings", _googleOAuthSettings == null ? null : _googleOAuthSettings.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("GoogleConnectorOAuth2.SUB_GenerateToken").withParams(params).execute(context);
		return result == null ? null : googleconnectoroauth2.proxies.TokenResponse.initialize(context, result);
	}
	public static java.lang.String sUB_GetGoogleRedirectURI(IContext context, googleconnectoroauth2.proxies.GoogleOAuthSettings _googleOAuthSettings)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleOAuthSettings", _googleOAuthSettings == null ? null : _googleOAuthSettings.getMendixObject());
		return (java.lang.String) Core.microflowCall("GoogleConnectorOAuth2.SUB_GetGoogleRedirectURI").withParams(params).execute(context);
	}
	public static void sUB_OAuth_Encryption(IContext context, googleconnectoroauth2.proxies.GoogleOAuthSettings _googleOAuthSettings)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleOAuthSettings", _googleOAuthSettings == null ? null : _googleOAuthSettings.getMendixObject());
		Core.microflowCall("GoogleConnectorOAuth2.SUB_OAuth_Encryption").withParams(params).execute(context);
	}
	public static googleconnectoroauth2.proxies.TokenResponse sUB_RefreshToken(IContext context, googleconnectoroauth2.proxies.GoogleOAuthSettings _googleOAuthSettings)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleOAuthSettings", _googleOAuthSettings == null ? null : _googleOAuthSettings.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("GoogleConnectorOAuth2.SUB_RefreshToken").withParams(params).execute(context);
		return result == null ? null : googleconnectoroauth2.proxies.TokenResponse.initialize(context, result);
	}
	public static java.lang.String sUB_RevokeAccess(IContext context, java.lang.String _accessToken)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AccessToken", _accessToken);
		return (java.lang.String) Core.microflowCall("GoogleConnectorOAuth2.SUB_RevokeAccess").withParams(params).execute(context);
	}
	public static boolean sUB_Scheduler_RefreshToken(IContext context, googleconnectoroauth2.proxies.GoogleOAuthSettings _googleOAuthSettings)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleOAuthSettings", _googleOAuthSettings == null ? null : _googleOAuthSettings.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("GoogleConnectorOAuth2.SUB_Scheduler_RefreshToken").withParams(params).execute(context);
	}
}
