// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googledriveconnector.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the GoogleDriveConnector module
	public static void aCT_Test_GoogleDrive_File_Copy(IContext context, googledriveconnector.proxies.TestGoogleDrive _testGoogleDrive)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestGoogleDrive", _testGoogleDrive == null ? null : _testGoogleDrive.getMendixObject());
		Core.microflowCall("GoogleDriveConnector.ACT_Test_GoogleDrive_File_Copy").withParams(params).execute(context);
	}
	public static void aCT_Test_GoogleDrive_File_Create(IContext context, googledriveconnector.proxies.TestGoogleDrive _testGoogleDrive)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestGoogleDrive", _testGoogleDrive == null ? null : _testGoogleDrive.getMendixObject());
		Core.microflowCall("GoogleDriveConnector.ACT_Test_GoogleDrive_File_Create").withParams(params).execute(context);
	}
	public static void aCT_Test_GoogleDrive_File_Delete(IContext context, googledriveconnector.proxies.TestGoogleDrive _testGoogleDrive)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestGoogleDrive", _testGoogleDrive == null ? null : _testGoogleDrive.getMendixObject());
		Core.microflowCall("GoogleDriveConnector.ACT_Test_GoogleDrive_File_Delete").withParams(params).execute(context);
	}
	public static void aCT_Test_GoogleDrive_File_Get(IContext context, googledriveconnector.proxies.TestGoogleDrive _testGoogleDrive)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestGoogleDrive", _testGoogleDrive == null ? null : _testGoogleDrive.getMendixObject());
		Core.microflowCall("GoogleDriveConnector.ACT_Test_GoogleDrive_File_Get").withParams(params).execute(context);
	}
	public static void aCT_Test_GoogleDrive_File_GetAsDocument(IContext context, googledriveconnector.proxies.GoogleDriveFile _googleDriveFile)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleDriveFile", _googleDriveFile == null ? null : _googleDriveFile.getMendixObject());
		Core.microflowCall("GoogleDriveConnector.ACT_Test_GoogleDrive_File_GetAsDocument").withParams(params).execute(context);
	}
	public static void aCT_Test_GoogleDrive_File_List(IContext context, googledriveconnector.proxies.TestGoogleDrive _testGoogleDrive)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestGoogleDrive", _testGoogleDrive == null ? null : _testGoogleDrive.getMendixObject());
		Core.microflowCall("GoogleDriveConnector.ACT_Test_GoogleDrive_File_List").withParams(params).execute(context);
	}
	public static void aCT_Test_GoogleDrive_File_Update(IContext context, googledriveconnector.proxies.TestGoogleDrive _testGoogleDrive)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestGoogleDrive", _testGoogleDrive == null ? null : _testGoogleDrive.getMendixObject());
		Core.microflowCall("GoogleDriveConnector.ACT_Test_GoogleDrive_File_Update").withParams(params).execute(context);
	}
	public static java.lang.String sUB_Drive_File_Copy(IContext context, java.lang.String _accessToken, java.lang.String _fileID, java.lang.String _body)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AccessToken", _accessToken);
		params.put("FileID", _fileID);
		params.put("Body", _body);
		return (java.lang.String) Core.microflowCall("GoogleDriveConnector.SUB_Drive_File_Copy").withParams(params).execute(context);
	}
	public static java.lang.String sUB_Drive_File_Create(IContext context, java.lang.String _accessToken, system.proxies.FileDocument _fileDocument, java.lang.String _metadata_JSON)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AccessToken", _accessToken);
		params.put("FileDocument", _fileDocument == null ? null : _fileDocument.getMendixObject());
		params.put("Metadata_JSON", _metadata_JSON);
		return (java.lang.String) Core.microflowCall("GoogleDriveConnector.SUB_Drive_File_Create").withParams(params).execute(context);
	}
	public static java.lang.Long sUB_Drive_File_Delete(IContext context, java.lang.String _accessToken, java.lang.String _fileID)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AccessToken", _accessToken);
		params.put("FileID", _fileID);
		return (java.lang.Long) Core.microflowCall("GoogleDriveConnector.SUB_Drive_File_Delete").withParams(params).execute(context);
	}
	public static java.lang.String sUB_Drive_File_Get(IContext context, java.lang.String _accessToken, java.lang.String _fileID, java.lang.String _params)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AccessToken", _accessToken);
		params.put("FileID", _fileID);
		params.put("Params", _params);
		return (java.lang.String) Core.microflowCall("GoogleDriveConnector.SUB_Drive_File_Get").withParams(params).execute(context);
	}
	public static googledriveconnector.proxies.Doc sUB_Drive_File_GetAsDocument(IContext context, java.lang.String _accessToken, java.lang.String _fileID, java.lang.String _params)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AccessToken", _accessToken);
		params.put("FileID", _fileID);
		params.put("Params", _params);
		IMendixObject result = (IMendixObject)Core.microflowCall("GoogleDriveConnector.SUB_Drive_File_GetAsDocument").withParams(params).execute(context);
		return result == null ? null : googledriveconnector.proxies.Doc.initialize(context, result);
	}
	public static googledriveconnector.proxies.GoogleDriveListRoot sUB_Drive_File_List(IContext context, java.lang.String _accessToken, java.lang.String _params)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AccessToken", _accessToken);
		params.put("Params", _params);
		IMendixObject result = (IMendixObject)Core.microflowCall("GoogleDriveConnector.SUB_Drive_File_List").withParams(params).execute(context);
		return result == null ? null : googledriveconnector.proxies.GoogleDriveListRoot.initialize(context, result);
	}
	public static java.lang.String sUB_Drive_File_Update(IContext context, java.lang.String _accessToken, system.proxies.FileDocument _fileDocument, java.lang.String _jSONContent, java.lang.String _fileID)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AccessToken", _accessToken);
		params.put("FileDocument", _fileDocument == null ? null : _fileDocument.getMendixObject());
		params.put("JSONContent", _jSONContent);
		params.put("FileID", _fileID);
		return (java.lang.String) Core.microflowCall("GoogleDriveConnector.SUB_Drive_File_Update").withParams(params).execute(context);
	}
	public static java.lang.String sUB_Generate_Param_List(IContext context, googledriveconnector.proxies.TestGoogleDrive _testGoogleDrive)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestGoogleDrive", _testGoogleDrive == null ? null : _testGoogleDrive.getMendixObject());
		return (java.lang.String) Core.microflowCall("GoogleDriveConnector.SUB_Generate_Param_List").withParams(params).execute(context);
	}
}
