// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googledriveconnector.proxies;

public class Capabilities
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject capabilitiesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GoogleDriveConnector.Capabilities";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CanChangeViewersCanCopyContent("CanChangeViewersCanCopyContent"),
		CanEdit("CanEdit"),
		CanCopy("CanCopy"),
		CanComment("CanComment"),
		CanAddChildren("CanAddChildren"),
		CanDelete("CanDelete"),
		CanDownload("CanDownload"),
		CanListChildren("CanListChildren"),
		CanRemoveChildren("CanRemoveChildren"),
		CanRename("CanRename"),
		CanTrash("CanTrash"),
		CanReadRevisions("CanReadRevisions"),
		CanChangeCopyRequiresWriterPermission("CanChangeCopyRequiresWriterPermission"),
		CanMoveItemIntoTeamDrive("CanMoveItemIntoTeamDrive"),
		CanUntrash("CanUntrash"),
		CanModifyContent("CanModifyContent"),
		CanMoveItemOutOfDrive("CanMoveItemOutOfDrive"),
		CanAddMyDriveParent("CanAddMyDriveParent"),
		CanRemoveMyDriveParent("CanRemoveMyDriveParent"),
		CanMoveItemWithinDrive("CanMoveItemWithinDrive"),
		CanShare("CanShare"),
		CanMoveChildrenWithinDrive("CanMoveChildrenWithinDrive"),
		CanModifyContentRestriction("CanModifyContentRestriction"),
		CanChangeSecurityUpdateEnabled("CanChangeSecurityUpdateEnabled"),
		CanAcceptOwnership("CanAcceptOwnership"),
		CanReadLabels("CanReadLabels"),
		CanModifyLabels("CanModifyLabels"),
		Capabilities_GoogleDriveFile("GoogleDriveConnector.Capabilities_GoogleDriveFile");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Capabilities(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Capabilities(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject capabilitiesMendixObject)
	{
		if (capabilitiesMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, capabilitiesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.capabilitiesMendixObject = capabilitiesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Capabilities.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static googledriveconnector.proxies.Capabilities initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return googledriveconnector.proxies.Capabilities.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static googledriveconnector.proxies.Capabilities initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new googledriveconnector.proxies.Capabilities(context, mendixObject);
	}

	public static googledriveconnector.proxies.Capabilities load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return googledriveconnector.proxies.Capabilities.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CanChangeViewersCanCopyContent
	 */
	public final java.lang.Boolean getCanChangeViewersCanCopyContent()
	{
		return getCanChangeViewersCanCopyContent(getContext());
	}

	/**
	 * @param context
	 * @return value of CanChangeViewersCanCopyContent
	 */
	public final java.lang.Boolean getCanChangeViewersCanCopyContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanChangeViewersCanCopyContent.toString());
	}

	/**
	 * Set value of CanChangeViewersCanCopyContent
	 * @param canchangeviewerscancopycontent
	 */
	public final void setCanChangeViewersCanCopyContent(java.lang.Boolean canchangeviewerscancopycontent)
	{
		setCanChangeViewersCanCopyContent(getContext(), canchangeviewerscancopycontent);
	}

	/**
	 * Set value of CanChangeViewersCanCopyContent
	 * @param context
	 * @param canchangeviewerscancopycontent
	 */
	public final void setCanChangeViewersCanCopyContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canchangeviewerscancopycontent)
	{
		getMendixObject().setValue(context, MemberNames.CanChangeViewersCanCopyContent.toString(), canchangeviewerscancopycontent);
	}

	/**
	 * @return value of CanEdit
	 */
	public final java.lang.Boolean getCanEdit()
	{
		return getCanEdit(getContext());
	}

	/**
	 * @param context
	 * @return value of CanEdit
	 */
	public final java.lang.Boolean getCanEdit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanEdit.toString());
	}

	/**
	 * Set value of CanEdit
	 * @param canedit
	 */
	public final void setCanEdit(java.lang.Boolean canedit)
	{
		setCanEdit(getContext(), canedit);
	}

	/**
	 * Set value of CanEdit
	 * @param context
	 * @param canedit
	 */
	public final void setCanEdit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canedit)
	{
		getMendixObject().setValue(context, MemberNames.CanEdit.toString(), canedit);
	}

	/**
	 * @return value of CanCopy
	 */
	public final java.lang.Boolean getCanCopy()
	{
		return getCanCopy(getContext());
	}

	/**
	 * @param context
	 * @return value of CanCopy
	 */
	public final java.lang.Boolean getCanCopy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanCopy.toString());
	}

	/**
	 * Set value of CanCopy
	 * @param cancopy
	 */
	public final void setCanCopy(java.lang.Boolean cancopy)
	{
		setCanCopy(getContext(), cancopy);
	}

	/**
	 * Set value of CanCopy
	 * @param context
	 * @param cancopy
	 */
	public final void setCanCopy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean cancopy)
	{
		getMendixObject().setValue(context, MemberNames.CanCopy.toString(), cancopy);
	}

	/**
	 * @return value of CanComment
	 */
	public final java.lang.Boolean getCanComment()
	{
		return getCanComment(getContext());
	}

	/**
	 * @param context
	 * @return value of CanComment
	 */
	public final java.lang.Boolean getCanComment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanComment.toString());
	}

	/**
	 * Set value of CanComment
	 * @param cancomment
	 */
	public final void setCanComment(java.lang.Boolean cancomment)
	{
		setCanComment(getContext(), cancomment);
	}

	/**
	 * Set value of CanComment
	 * @param context
	 * @param cancomment
	 */
	public final void setCanComment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean cancomment)
	{
		getMendixObject().setValue(context, MemberNames.CanComment.toString(), cancomment);
	}

	/**
	 * @return value of CanAddChildren
	 */
	public final java.lang.Boolean getCanAddChildren()
	{
		return getCanAddChildren(getContext());
	}

	/**
	 * @param context
	 * @return value of CanAddChildren
	 */
	public final java.lang.Boolean getCanAddChildren(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanAddChildren.toString());
	}

	/**
	 * Set value of CanAddChildren
	 * @param canaddchildren
	 */
	public final void setCanAddChildren(java.lang.Boolean canaddchildren)
	{
		setCanAddChildren(getContext(), canaddchildren);
	}

	/**
	 * Set value of CanAddChildren
	 * @param context
	 * @param canaddchildren
	 */
	public final void setCanAddChildren(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canaddchildren)
	{
		getMendixObject().setValue(context, MemberNames.CanAddChildren.toString(), canaddchildren);
	}

	/**
	 * @return value of CanDelete
	 */
	public final java.lang.Boolean getCanDelete()
	{
		return getCanDelete(getContext());
	}

	/**
	 * @param context
	 * @return value of CanDelete
	 */
	public final java.lang.Boolean getCanDelete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanDelete.toString());
	}

	/**
	 * Set value of CanDelete
	 * @param candelete
	 */
	public final void setCanDelete(java.lang.Boolean candelete)
	{
		setCanDelete(getContext(), candelete);
	}

	/**
	 * Set value of CanDelete
	 * @param context
	 * @param candelete
	 */
	public final void setCanDelete(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean candelete)
	{
		getMendixObject().setValue(context, MemberNames.CanDelete.toString(), candelete);
	}

	/**
	 * @return value of CanDownload
	 */
	public final java.lang.Boolean getCanDownload()
	{
		return getCanDownload(getContext());
	}

	/**
	 * @param context
	 * @return value of CanDownload
	 */
	public final java.lang.Boolean getCanDownload(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanDownload.toString());
	}

	/**
	 * Set value of CanDownload
	 * @param candownload
	 */
	public final void setCanDownload(java.lang.Boolean candownload)
	{
		setCanDownload(getContext(), candownload);
	}

	/**
	 * Set value of CanDownload
	 * @param context
	 * @param candownload
	 */
	public final void setCanDownload(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean candownload)
	{
		getMendixObject().setValue(context, MemberNames.CanDownload.toString(), candownload);
	}

	/**
	 * @return value of CanListChildren
	 */
	public final java.lang.Boolean getCanListChildren()
	{
		return getCanListChildren(getContext());
	}

	/**
	 * @param context
	 * @return value of CanListChildren
	 */
	public final java.lang.Boolean getCanListChildren(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanListChildren.toString());
	}

	/**
	 * Set value of CanListChildren
	 * @param canlistchildren
	 */
	public final void setCanListChildren(java.lang.Boolean canlistchildren)
	{
		setCanListChildren(getContext(), canlistchildren);
	}

	/**
	 * Set value of CanListChildren
	 * @param context
	 * @param canlistchildren
	 */
	public final void setCanListChildren(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canlistchildren)
	{
		getMendixObject().setValue(context, MemberNames.CanListChildren.toString(), canlistchildren);
	}

	/**
	 * @return value of CanRemoveChildren
	 */
	public final java.lang.Boolean getCanRemoveChildren()
	{
		return getCanRemoveChildren(getContext());
	}

	/**
	 * @param context
	 * @return value of CanRemoveChildren
	 */
	public final java.lang.Boolean getCanRemoveChildren(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanRemoveChildren.toString());
	}

	/**
	 * Set value of CanRemoveChildren
	 * @param canremovechildren
	 */
	public final void setCanRemoveChildren(java.lang.Boolean canremovechildren)
	{
		setCanRemoveChildren(getContext(), canremovechildren);
	}

	/**
	 * Set value of CanRemoveChildren
	 * @param context
	 * @param canremovechildren
	 */
	public final void setCanRemoveChildren(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canremovechildren)
	{
		getMendixObject().setValue(context, MemberNames.CanRemoveChildren.toString(), canremovechildren);
	}

	/**
	 * @return value of CanRename
	 */
	public final java.lang.Boolean getCanRename()
	{
		return getCanRename(getContext());
	}

	/**
	 * @param context
	 * @return value of CanRename
	 */
	public final java.lang.Boolean getCanRename(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanRename.toString());
	}

	/**
	 * Set value of CanRename
	 * @param canrename
	 */
	public final void setCanRename(java.lang.Boolean canrename)
	{
		setCanRename(getContext(), canrename);
	}

	/**
	 * Set value of CanRename
	 * @param context
	 * @param canrename
	 */
	public final void setCanRename(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canrename)
	{
		getMendixObject().setValue(context, MemberNames.CanRename.toString(), canrename);
	}

	/**
	 * @return value of CanTrash
	 */
	public final java.lang.Boolean getCanTrash()
	{
		return getCanTrash(getContext());
	}

	/**
	 * @param context
	 * @return value of CanTrash
	 */
	public final java.lang.Boolean getCanTrash(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanTrash.toString());
	}

	/**
	 * Set value of CanTrash
	 * @param cantrash
	 */
	public final void setCanTrash(java.lang.Boolean cantrash)
	{
		setCanTrash(getContext(), cantrash);
	}

	/**
	 * Set value of CanTrash
	 * @param context
	 * @param cantrash
	 */
	public final void setCanTrash(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean cantrash)
	{
		getMendixObject().setValue(context, MemberNames.CanTrash.toString(), cantrash);
	}

	/**
	 * @return value of CanReadRevisions
	 */
	public final java.lang.Boolean getCanReadRevisions()
	{
		return getCanReadRevisions(getContext());
	}

	/**
	 * @param context
	 * @return value of CanReadRevisions
	 */
	public final java.lang.Boolean getCanReadRevisions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanReadRevisions.toString());
	}

	/**
	 * Set value of CanReadRevisions
	 * @param canreadrevisions
	 */
	public final void setCanReadRevisions(java.lang.Boolean canreadrevisions)
	{
		setCanReadRevisions(getContext(), canreadrevisions);
	}

	/**
	 * Set value of CanReadRevisions
	 * @param context
	 * @param canreadrevisions
	 */
	public final void setCanReadRevisions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canreadrevisions)
	{
		getMendixObject().setValue(context, MemberNames.CanReadRevisions.toString(), canreadrevisions);
	}

	/**
	 * @return value of CanChangeCopyRequiresWriterPermission
	 */
	public final java.lang.Boolean getCanChangeCopyRequiresWriterPermission()
	{
		return getCanChangeCopyRequiresWriterPermission(getContext());
	}

	/**
	 * @param context
	 * @return value of CanChangeCopyRequiresWriterPermission
	 */
	public final java.lang.Boolean getCanChangeCopyRequiresWriterPermission(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanChangeCopyRequiresWriterPermission.toString());
	}

	/**
	 * Set value of CanChangeCopyRequiresWriterPermission
	 * @param canchangecopyrequireswriterpermission
	 */
	public final void setCanChangeCopyRequiresWriterPermission(java.lang.Boolean canchangecopyrequireswriterpermission)
	{
		setCanChangeCopyRequiresWriterPermission(getContext(), canchangecopyrequireswriterpermission);
	}

	/**
	 * Set value of CanChangeCopyRequiresWriterPermission
	 * @param context
	 * @param canchangecopyrequireswriterpermission
	 */
	public final void setCanChangeCopyRequiresWriterPermission(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canchangecopyrequireswriterpermission)
	{
		getMendixObject().setValue(context, MemberNames.CanChangeCopyRequiresWriterPermission.toString(), canchangecopyrequireswriterpermission);
	}

	/**
	 * @return value of CanMoveItemIntoTeamDrive
	 */
	public final java.lang.Boolean getCanMoveItemIntoTeamDrive()
	{
		return getCanMoveItemIntoTeamDrive(getContext());
	}

	/**
	 * @param context
	 * @return value of CanMoveItemIntoTeamDrive
	 */
	public final java.lang.Boolean getCanMoveItemIntoTeamDrive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanMoveItemIntoTeamDrive.toString());
	}

	/**
	 * Set value of CanMoveItemIntoTeamDrive
	 * @param canmoveitemintoteamdrive
	 */
	public final void setCanMoveItemIntoTeamDrive(java.lang.Boolean canmoveitemintoteamdrive)
	{
		setCanMoveItemIntoTeamDrive(getContext(), canmoveitemintoteamdrive);
	}

	/**
	 * Set value of CanMoveItemIntoTeamDrive
	 * @param context
	 * @param canmoveitemintoteamdrive
	 */
	public final void setCanMoveItemIntoTeamDrive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canmoveitemintoteamdrive)
	{
		getMendixObject().setValue(context, MemberNames.CanMoveItemIntoTeamDrive.toString(), canmoveitemintoteamdrive);
	}

	/**
	 * @return value of CanUntrash
	 */
	public final java.lang.Boolean getCanUntrash()
	{
		return getCanUntrash(getContext());
	}

	/**
	 * @param context
	 * @return value of CanUntrash
	 */
	public final java.lang.Boolean getCanUntrash(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanUntrash.toString());
	}

	/**
	 * Set value of CanUntrash
	 * @param canuntrash
	 */
	public final void setCanUntrash(java.lang.Boolean canuntrash)
	{
		setCanUntrash(getContext(), canuntrash);
	}

	/**
	 * Set value of CanUntrash
	 * @param context
	 * @param canuntrash
	 */
	public final void setCanUntrash(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canuntrash)
	{
		getMendixObject().setValue(context, MemberNames.CanUntrash.toString(), canuntrash);
	}

	/**
	 * @return value of CanModifyContent
	 */
	public final java.lang.Boolean getCanModifyContent()
	{
		return getCanModifyContent(getContext());
	}

	/**
	 * @param context
	 * @return value of CanModifyContent
	 */
	public final java.lang.Boolean getCanModifyContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanModifyContent.toString());
	}

	/**
	 * Set value of CanModifyContent
	 * @param canmodifycontent
	 */
	public final void setCanModifyContent(java.lang.Boolean canmodifycontent)
	{
		setCanModifyContent(getContext(), canmodifycontent);
	}

	/**
	 * Set value of CanModifyContent
	 * @param context
	 * @param canmodifycontent
	 */
	public final void setCanModifyContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canmodifycontent)
	{
		getMendixObject().setValue(context, MemberNames.CanModifyContent.toString(), canmodifycontent);
	}

	/**
	 * @return value of CanMoveItemOutOfDrive
	 */
	public final java.lang.Boolean getCanMoveItemOutOfDrive()
	{
		return getCanMoveItemOutOfDrive(getContext());
	}

	/**
	 * @param context
	 * @return value of CanMoveItemOutOfDrive
	 */
	public final java.lang.Boolean getCanMoveItemOutOfDrive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanMoveItemOutOfDrive.toString());
	}

	/**
	 * Set value of CanMoveItemOutOfDrive
	 * @param canmoveitemoutofdrive
	 */
	public final void setCanMoveItemOutOfDrive(java.lang.Boolean canmoveitemoutofdrive)
	{
		setCanMoveItemOutOfDrive(getContext(), canmoveitemoutofdrive);
	}

	/**
	 * Set value of CanMoveItemOutOfDrive
	 * @param context
	 * @param canmoveitemoutofdrive
	 */
	public final void setCanMoveItemOutOfDrive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canmoveitemoutofdrive)
	{
		getMendixObject().setValue(context, MemberNames.CanMoveItemOutOfDrive.toString(), canmoveitemoutofdrive);
	}

	/**
	 * @return value of CanAddMyDriveParent
	 */
	public final java.lang.Boolean getCanAddMyDriveParent()
	{
		return getCanAddMyDriveParent(getContext());
	}

	/**
	 * @param context
	 * @return value of CanAddMyDriveParent
	 */
	public final java.lang.Boolean getCanAddMyDriveParent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanAddMyDriveParent.toString());
	}

	/**
	 * Set value of CanAddMyDriveParent
	 * @param canaddmydriveparent
	 */
	public final void setCanAddMyDriveParent(java.lang.Boolean canaddmydriveparent)
	{
		setCanAddMyDriveParent(getContext(), canaddmydriveparent);
	}

	/**
	 * Set value of CanAddMyDriveParent
	 * @param context
	 * @param canaddmydriveparent
	 */
	public final void setCanAddMyDriveParent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canaddmydriveparent)
	{
		getMendixObject().setValue(context, MemberNames.CanAddMyDriveParent.toString(), canaddmydriveparent);
	}

	/**
	 * @return value of CanRemoveMyDriveParent
	 */
	public final java.lang.Boolean getCanRemoveMyDriveParent()
	{
		return getCanRemoveMyDriveParent(getContext());
	}

	/**
	 * @param context
	 * @return value of CanRemoveMyDriveParent
	 */
	public final java.lang.Boolean getCanRemoveMyDriveParent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanRemoveMyDriveParent.toString());
	}

	/**
	 * Set value of CanRemoveMyDriveParent
	 * @param canremovemydriveparent
	 */
	public final void setCanRemoveMyDriveParent(java.lang.Boolean canremovemydriveparent)
	{
		setCanRemoveMyDriveParent(getContext(), canremovemydriveparent);
	}

	/**
	 * Set value of CanRemoveMyDriveParent
	 * @param context
	 * @param canremovemydriveparent
	 */
	public final void setCanRemoveMyDriveParent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canremovemydriveparent)
	{
		getMendixObject().setValue(context, MemberNames.CanRemoveMyDriveParent.toString(), canremovemydriveparent);
	}

	/**
	 * @return value of CanMoveItemWithinDrive
	 */
	public final java.lang.Boolean getCanMoveItemWithinDrive()
	{
		return getCanMoveItemWithinDrive(getContext());
	}

	/**
	 * @param context
	 * @return value of CanMoveItemWithinDrive
	 */
	public final java.lang.Boolean getCanMoveItemWithinDrive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanMoveItemWithinDrive.toString());
	}

	/**
	 * Set value of CanMoveItemWithinDrive
	 * @param canmoveitemwithindrive
	 */
	public final void setCanMoveItemWithinDrive(java.lang.Boolean canmoveitemwithindrive)
	{
		setCanMoveItemWithinDrive(getContext(), canmoveitemwithindrive);
	}

	/**
	 * Set value of CanMoveItemWithinDrive
	 * @param context
	 * @param canmoveitemwithindrive
	 */
	public final void setCanMoveItemWithinDrive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canmoveitemwithindrive)
	{
		getMendixObject().setValue(context, MemberNames.CanMoveItemWithinDrive.toString(), canmoveitemwithindrive);
	}

	/**
	 * @return value of CanShare
	 */
	public final java.lang.Boolean getCanShare()
	{
		return getCanShare(getContext());
	}

	/**
	 * @param context
	 * @return value of CanShare
	 */
	public final java.lang.Boolean getCanShare(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanShare.toString());
	}

	/**
	 * Set value of CanShare
	 * @param canshare
	 */
	public final void setCanShare(java.lang.Boolean canshare)
	{
		setCanShare(getContext(), canshare);
	}

	/**
	 * Set value of CanShare
	 * @param context
	 * @param canshare
	 */
	public final void setCanShare(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canshare)
	{
		getMendixObject().setValue(context, MemberNames.CanShare.toString(), canshare);
	}

	/**
	 * @return value of CanMoveChildrenWithinDrive
	 */
	public final java.lang.Boolean getCanMoveChildrenWithinDrive()
	{
		return getCanMoveChildrenWithinDrive(getContext());
	}

	/**
	 * @param context
	 * @return value of CanMoveChildrenWithinDrive
	 */
	public final java.lang.Boolean getCanMoveChildrenWithinDrive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanMoveChildrenWithinDrive.toString());
	}

	/**
	 * Set value of CanMoveChildrenWithinDrive
	 * @param canmovechildrenwithindrive
	 */
	public final void setCanMoveChildrenWithinDrive(java.lang.Boolean canmovechildrenwithindrive)
	{
		setCanMoveChildrenWithinDrive(getContext(), canmovechildrenwithindrive);
	}

	/**
	 * Set value of CanMoveChildrenWithinDrive
	 * @param context
	 * @param canmovechildrenwithindrive
	 */
	public final void setCanMoveChildrenWithinDrive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canmovechildrenwithindrive)
	{
		getMendixObject().setValue(context, MemberNames.CanMoveChildrenWithinDrive.toString(), canmovechildrenwithindrive);
	}

	/**
	 * @return value of CanModifyContentRestriction
	 */
	public final java.lang.Boolean getCanModifyContentRestriction()
	{
		return getCanModifyContentRestriction(getContext());
	}

	/**
	 * @param context
	 * @return value of CanModifyContentRestriction
	 */
	public final java.lang.Boolean getCanModifyContentRestriction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanModifyContentRestriction.toString());
	}

	/**
	 * Set value of CanModifyContentRestriction
	 * @param canmodifycontentrestriction
	 */
	public final void setCanModifyContentRestriction(java.lang.Boolean canmodifycontentrestriction)
	{
		setCanModifyContentRestriction(getContext(), canmodifycontentrestriction);
	}

	/**
	 * Set value of CanModifyContentRestriction
	 * @param context
	 * @param canmodifycontentrestriction
	 */
	public final void setCanModifyContentRestriction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canmodifycontentrestriction)
	{
		getMendixObject().setValue(context, MemberNames.CanModifyContentRestriction.toString(), canmodifycontentrestriction);
	}

	/**
	 * @return value of CanChangeSecurityUpdateEnabled
	 */
	public final java.lang.Boolean getCanChangeSecurityUpdateEnabled()
	{
		return getCanChangeSecurityUpdateEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of CanChangeSecurityUpdateEnabled
	 */
	public final java.lang.Boolean getCanChangeSecurityUpdateEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanChangeSecurityUpdateEnabled.toString());
	}

	/**
	 * Set value of CanChangeSecurityUpdateEnabled
	 * @param canchangesecurityupdateenabled
	 */
	public final void setCanChangeSecurityUpdateEnabled(java.lang.Boolean canchangesecurityupdateenabled)
	{
		setCanChangeSecurityUpdateEnabled(getContext(), canchangesecurityupdateenabled);
	}

	/**
	 * Set value of CanChangeSecurityUpdateEnabled
	 * @param context
	 * @param canchangesecurityupdateenabled
	 */
	public final void setCanChangeSecurityUpdateEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canchangesecurityupdateenabled)
	{
		getMendixObject().setValue(context, MemberNames.CanChangeSecurityUpdateEnabled.toString(), canchangesecurityupdateenabled);
	}

	/**
	 * @return value of CanAcceptOwnership
	 */
	public final java.lang.Boolean getCanAcceptOwnership()
	{
		return getCanAcceptOwnership(getContext());
	}

	/**
	 * @param context
	 * @return value of CanAcceptOwnership
	 */
	public final java.lang.Boolean getCanAcceptOwnership(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanAcceptOwnership.toString());
	}

	/**
	 * Set value of CanAcceptOwnership
	 * @param canacceptownership
	 */
	public final void setCanAcceptOwnership(java.lang.Boolean canacceptownership)
	{
		setCanAcceptOwnership(getContext(), canacceptownership);
	}

	/**
	 * Set value of CanAcceptOwnership
	 * @param context
	 * @param canacceptownership
	 */
	public final void setCanAcceptOwnership(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canacceptownership)
	{
		getMendixObject().setValue(context, MemberNames.CanAcceptOwnership.toString(), canacceptownership);
	}

	/**
	 * @return value of CanReadLabels
	 */
	public final java.lang.Boolean getCanReadLabels()
	{
		return getCanReadLabels(getContext());
	}

	/**
	 * @param context
	 * @return value of CanReadLabels
	 */
	public final java.lang.Boolean getCanReadLabels(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanReadLabels.toString());
	}

	/**
	 * Set value of CanReadLabels
	 * @param canreadlabels
	 */
	public final void setCanReadLabels(java.lang.Boolean canreadlabels)
	{
		setCanReadLabels(getContext(), canreadlabels);
	}

	/**
	 * Set value of CanReadLabels
	 * @param context
	 * @param canreadlabels
	 */
	public final void setCanReadLabels(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canreadlabels)
	{
		getMendixObject().setValue(context, MemberNames.CanReadLabels.toString(), canreadlabels);
	}

	/**
	 * @return value of CanModifyLabels
	 */
	public final java.lang.Boolean getCanModifyLabels()
	{
		return getCanModifyLabels(getContext());
	}

	/**
	 * @param context
	 * @return value of CanModifyLabels
	 */
	public final java.lang.Boolean getCanModifyLabels(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CanModifyLabels.toString());
	}

	/**
	 * Set value of CanModifyLabels
	 * @param canmodifylabels
	 */
	public final void setCanModifyLabels(java.lang.Boolean canmodifylabels)
	{
		setCanModifyLabels(getContext(), canmodifylabels);
	}

	/**
	 * Set value of CanModifyLabels
	 * @param context
	 * @param canmodifylabels
	 */
	public final void setCanModifyLabels(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean canmodifylabels)
	{
		getMendixObject().setValue(context, MemberNames.CanModifyLabels.toString(), canmodifylabels);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Capabilities_GoogleDriveFile
	 */
	public final googledriveconnector.proxies.GoogleDriveFile getCapabilities_GoogleDriveFile() throws com.mendix.core.CoreException
	{
		return getCapabilities_GoogleDriveFile(getContext());
	}

	/**
	 * @param context
	 * @return value of Capabilities_GoogleDriveFile
	 * @throws com.mendix.core.CoreException
	 */
	public final googledriveconnector.proxies.GoogleDriveFile getCapabilities_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googledriveconnector.proxies.GoogleDriveFile result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Capabilities_GoogleDriveFile.toString());
		if (identifier != null) {
			result = googledriveconnector.proxies.GoogleDriveFile.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Capabilities_GoogleDriveFile
	 * @param capabilities_googledrivefile
	 */
	public final void setCapabilities_GoogleDriveFile(googledriveconnector.proxies.GoogleDriveFile capabilities_googledrivefile)
	{
		setCapabilities_GoogleDriveFile(getContext(), capabilities_googledrivefile);
	}

	/**
	 * Set value of Capabilities_GoogleDriveFile
	 * @param context
	 * @param capabilities_googledrivefile
	 */
	public final void setCapabilities_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context, googledriveconnector.proxies.GoogleDriveFile capabilities_googledrivefile)
	{
		if (capabilities_googledrivefile == null) {
			getMendixObject().setValue(context, MemberNames.Capabilities_GoogleDriveFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Capabilities_GoogleDriveFile.toString(), capabilities_googledrivefile.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return capabilitiesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final googledriveconnector.proxies.Capabilities that = (googledriveconnector.proxies.Capabilities) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
