// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googledriveconnector.proxies;

public class FilesList
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject filesListMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GoogleDriveConnector.FilesList";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FilesList_GoogleDriveListRoot("GoogleDriveConnector.FilesList_GoogleDriveListRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FilesList(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FilesList(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject filesListMendixObject)
	{
		if (filesListMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, filesListMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.filesListMendixObject = filesListMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'FilesList.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static googledriveconnector.proxies.FilesList initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return googledriveconnector.proxies.FilesList.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static googledriveconnector.proxies.FilesList initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new googledriveconnector.proxies.FilesList(context, mendixObject);
	}

	public static googledriveconnector.proxies.FilesList load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return googledriveconnector.proxies.FilesList.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FilesList_GoogleDriveListRoot
	 */
	public final googledriveconnector.proxies.GoogleDriveListRoot getFilesList_GoogleDriveListRoot() throws com.mendix.core.CoreException
	{
		return getFilesList_GoogleDriveListRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of FilesList_GoogleDriveListRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final googledriveconnector.proxies.GoogleDriveListRoot getFilesList_GoogleDriveListRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googledriveconnector.proxies.GoogleDriveListRoot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FilesList_GoogleDriveListRoot.toString());
		if (identifier != null) {
			result = googledriveconnector.proxies.GoogleDriveListRoot.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FilesList_GoogleDriveListRoot
	 * @param fileslist_googledrivelistroot
	 */
	public final void setFilesList_GoogleDriveListRoot(googledriveconnector.proxies.GoogleDriveListRoot fileslist_googledrivelistroot)
	{
		setFilesList_GoogleDriveListRoot(getContext(), fileslist_googledrivelistroot);
	}

	/**
	 * Set value of FilesList_GoogleDriveListRoot
	 * @param context
	 * @param fileslist_googledrivelistroot
	 */
	public final void setFilesList_GoogleDriveListRoot(com.mendix.systemwideinterfaces.core.IContext context, googledriveconnector.proxies.GoogleDriveListRoot fileslist_googledrivelistroot)
	{
		if (fileslist_googledrivelistroot == null) {
			getMendixObject().setValue(context, MemberNames.FilesList_GoogleDriveListRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FilesList_GoogleDriveListRoot.toString(), fileslist_googledrivelistroot.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return filesListMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final googledriveconnector.proxies.FilesList that = (googledriveconnector.proxies.FilesList) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
