// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googledriveconnector.proxies;

public class GoogleDriveFile
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject googleDriveFileMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GoogleDriveConnector.GoogleDriveFile";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Kind("Kind"),
		FileExtension("FileExtension"),
		CopyRequiresWriterPermission("CopyRequiresWriterPermission"),
		Md5Checksum("Md5Checksum"),
		WritersCanShare("WritersCanShare"),
		ViewedByMe("ViewedByMe"),
		MimeType("MimeType"),
		ThumbnailLink("ThumbnailLink"),
		IconLink("IconLink"),
		Shared("Shared"),
		HeadRevisionId("HeadRevisionId"),
		WebViewLink("WebViewLink"),
		WebContentLink("WebContentLink"),
		Size("Size"),
		ViewersCanCopyContent("ViewersCanCopyContent"),
		HasThumbnail("HasThumbnail"),
		_id("_id"),
		Name("Name"),
		Description("Description"),
		Starred("Starred"),
		Trashed("Trashed"),
		ExplicitlyTrashed("ExplicitlyTrashed"),
		CreatedTime("CreatedTime"),
		ModifiedTime("ModifiedTime"),
		ModifiedByMeTime("ModifiedByMeTime"),
		QuotaBytesUsed("QuotaBytesUsed"),
		Version("Version"),
		OriginalFilename("OriginalFilename"),
		OwnedByMe("OwnedByMe"),
		FullFileExtension("FullFileExtension"),
		IsAppAuthorized("IsAppAuthorized"),
		ThumbnailVersion("ThumbnailVersion"),
		ModifiedByMe("ModifiedByMe"),
		Sha1Checksum("Sha1Checksum"),
		Sha256Checksum("Sha256Checksum"),
		ViewedByMeTime("ViewedByMeTime"),
		GoogleDriveFile_FilesList("GoogleDriveConnector.GoogleDriveFile_FilesList"),
		Parents_GoogleDriveFile("GoogleDriveConnector.Parents_GoogleDriveFile"),
		LastModifyingUser_GoogleDriveFile("GoogleDriveConnector.LastModifyingUser_GoogleDriveFile"),
		Owners_GoogleDriveFile("GoogleDriveConnector.Owners_GoogleDriveFile"),
		Permissions_GoogleDriveFile("GoogleDriveConnector.Permissions_GoogleDriveFile"),
		Spaces_GoogleDriveFile("GoogleDriveConnector.Spaces_GoogleDriveFile"),
		Capabilities_GoogleDriveFile("GoogleDriveConnector.Capabilities_GoogleDriveFile"),
		PermissionIds_GoogleDriveFile("GoogleDriveConnector.PermissionIds_GoogleDriveFile"),
		LinkShareMetadata_GoogleDriveFile("GoogleDriveConnector.LinkShareMetadata_GoogleDriveFile");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject googleDriveFileMendixObject)
	{
		if (googleDriveFileMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, googleDriveFileMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.googleDriveFileMendixObject = googleDriveFileMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GoogleDriveFile.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static googledriveconnector.proxies.GoogleDriveFile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return googledriveconnector.proxies.GoogleDriveFile.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static googledriveconnector.proxies.GoogleDriveFile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new googledriveconnector.proxies.GoogleDriveFile(context, mendixObject);
	}

	public static googledriveconnector.proxies.GoogleDriveFile load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return googledriveconnector.proxies.GoogleDriveFile.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Kind
	 */
	public final java.lang.String getKind()
	{
		return getKind(getContext());
	}

	/**
	 * @param context
	 * @return value of Kind
	 */
	public final java.lang.String getKind(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Kind.toString());
	}

	/**
	 * Set value of Kind
	 * @param kind
	 */
	public final void setKind(java.lang.String kind)
	{
		setKind(getContext(), kind);
	}

	/**
	 * Set value of Kind
	 * @param context
	 * @param kind
	 */
	public final void setKind(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kind)
	{
		getMendixObject().setValue(context, MemberNames.Kind.toString(), kind);
	}

	/**
	 * @return value of FileExtension
	 */
	public final java.lang.String getFileExtension()
	{
		return getFileExtension(getContext());
	}

	/**
	 * @param context
	 * @return value of FileExtension
	 */
	public final java.lang.String getFileExtension(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FileExtension.toString());
	}

	/**
	 * Set value of FileExtension
	 * @param fileextension
	 */
	public final void setFileExtension(java.lang.String fileextension)
	{
		setFileExtension(getContext(), fileextension);
	}

	/**
	 * Set value of FileExtension
	 * @param context
	 * @param fileextension
	 */
	public final void setFileExtension(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fileextension)
	{
		getMendixObject().setValue(context, MemberNames.FileExtension.toString(), fileextension);
	}

	/**
	 * @return value of CopyRequiresWriterPermission
	 */
	public final java.lang.Boolean getCopyRequiresWriterPermission()
	{
		return getCopyRequiresWriterPermission(getContext());
	}

	/**
	 * @param context
	 * @return value of CopyRequiresWriterPermission
	 */
	public final java.lang.Boolean getCopyRequiresWriterPermission(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CopyRequiresWriterPermission.toString());
	}

	/**
	 * Set value of CopyRequiresWriterPermission
	 * @param copyrequireswriterpermission
	 */
	public final void setCopyRequiresWriterPermission(java.lang.Boolean copyrequireswriterpermission)
	{
		setCopyRequiresWriterPermission(getContext(), copyrequireswriterpermission);
	}

	/**
	 * Set value of CopyRequiresWriterPermission
	 * @param context
	 * @param copyrequireswriterpermission
	 */
	public final void setCopyRequiresWriterPermission(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean copyrequireswriterpermission)
	{
		getMendixObject().setValue(context, MemberNames.CopyRequiresWriterPermission.toString(), copyrequireswriterpermission);
	}

	/**
	 * @return value of Md5Checksum
	 */
	public final java.lang.String getMd5Checksum()
	{
		return getMd5Checksum(getContext());
	}

	/**
	 * @param context
	 * @return value of Md5Checksum
	 */
	public final java.lang.String getMd5Checksum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Md5Checksum.toString());
	}

	/**
	 * Set value of Md5Checksum
	 * @param md5checksum
	 */
	public final void setMd5Checksum(java.lang.String md5checksum)
	{
		setMd5Checksum(getContext(), md5checksum);
	}

	/**
	 * Set value of Md5Checksum
	 * @param context
	 * @param md5checksum
	 */
	public final void setMd5Checksum(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String md5checksum)
	{
		getMendixObject().setValue(context, MemberNames.Md5Checksum.toString(), md5checksum);
	}

	/**
	 * @return value of WritersCanShare
	 */
	public final java.lang.Boolean getWritersCanShare()
	{
		return getWritersCanShare(getContext());
	}

	/**
	 * @param context
	 * @return value of WritersCanShare
	 */
	public final java.lang.Boolean getWritersCanShare(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WritersCanShare.toString());
	}

	/**
	 * Set value of WritersCanShare
	 * @param writerscanshare
	 */
	public final void setWritersCanShare(java.lang.Boolean writerscanshare)
	{
		setWritersCanShare(getContext(), writerscanshare);
	}

	/**
	 * Set value of WritersCanShare
	 * @param context
	 * @param writerscanshare
	 */
	public final void setWritersCanShare(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean writerscanshare)
	{
		getMendixObject().setValue(context, MemberNames.WritersCanShare.toString(), writerscanshare);
	}

	/**
	 * @return value of ViewedByMe
	 */
	public final java.lang.Boolean getViewedByMe()
	{
		return getViewedByMe(getContext());
	}

	/**
	 * @param context
	 * @return value of ViewedByMe
	 */
	public final java.lang.Boolean getViewedByMe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ViewedByMe.toString());
	}

	/**
	 * Set value of ViewedByMe
	 * @param viewedbyme
	 */
	public final void setViewedByMe(java.lang.Boolean viewedbyme)
	{
		setViewedByMe(getContext(), viewedbyme);
	}

	/**
	 * Set value of ViewedByMe
	 * @param context
	 * @param viewedbyme
	 */
	public final void setViewedByMe(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean viewedbyme)
	{
		getMendixObject().setValue(context, MemberNames.ViewedByMe.toString(), viewedbyme);
	}

	/**
	 * @return value of MimeType
	 */
	public final java.lang.String getMimeType()
	{
		return getMimeType(getContext());
	}

	/**
	 * @param context
	 * @return value of MimeType
	 */
	public final java.lang.String getMimeType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MimeType.toString());
	}

	/**
	 * Set value of MimeType
	 * @param mimetype
	 */
	public final void setMimeType(java.lang.String mimetype)
	{
		setMimeType(getContext(), mimetype);
	}

	/**
	 * Set value of MimeType
	 * @param context
	 * @param mimetype
	 */
	public final void setMimeType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mimetype)
	{
		getMendixObject().setValue(context, MemberNames.MimeType.toString(), mimetype);
	}

	/**
	 * @return value of ThumbnailLink
	 */
	public final java.lang.String getThumbnailLink()
	{
		return getThumbnailLink(getContext());
	}

	/**
	 * @param context
	 * @return value of ThumbnailLink
	 */
	public final java.lang.String getThumbnailLink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ThumbnailLink.toString());
	}

	/**
	 * Set value of ThumbnailLink
	 * @param thumbnaillink
	 */
	public final void setThumbnailLink(java.lang.String thumbnaillink)
	{
		setThumbnailLink(getContext(), thumbnaillink);
	}

	/**
	 * Set value of ThumbnailLink
	 * @param context
	 * @param thumbnaillink
	 */
	public final void setThumbnailLink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String thumbnaillink)
	{
		getMendixObject().setValue(context, MemberNames.ThumbnailLink.toString(), thumbnaillink);
	}

	/**
	 * @return value of IconLink
	 */
	public final java.lang.String getIconLink()
	{
		return getIconLink(getContext());
	}

	/**
	 * @param context
	 * @return value of IconLink
	 */
	public final java.lang.String getIconLink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IconLink.toString());
	}

	/**
	 * Set value of IconLink
	 * @param iconlink
	 */
	public final void setIconLink(java.lang.String iconlink)
	{
		setIconLink(getContext(), iconlink);
	}

	/**
	 * Set value of IconLink
	 * @param context
	 * @param iconlink
	 */
	public final void setIconLink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iconlink)
	{
		getMendixObject().setValue(context, MemberNames.IconLink.toString(), iconlink);
	}

	/**
	 * @return value of Shared
	 */
	public final java.lang.Boolean getShared()
	{
		return getShared(getContext());
	}

	/**
	 * @param context
	 * @return value of Shared
	 */
	public final java.lang.Boolean getShared(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Shared.toString());
	}

	/**
	 * Set value of Shared
	 * @param shared
	 */
	public final void setShared(java.lang.Boolean shared)
	{
		setShared(getContext(), shared);
	}

	/**
	 * Set value of Shared
	 * @param context
	 * @param shared
	 */
	public final void setShared(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean shared)
	{
		getMendixObject().setValue(context, MemberNames.Shared.toString(), shared);
	}

	/**
	 * @return value of HeadRevisionId
	 */
	public final java.lang.String getHeadRevisionId()
	{
		return getHeadRevisionId(getContext());
	}

	/**
	 * @param context
	 * @return value of HeadRevisionId
	 */
	public final java.lang.String getHeadRevisionId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HeadRevisionId.toString());
	}

	/**
	 * Set value of HeadRevisionId
	 * @param headrevisionid
	 */
	public final void setHeadRevisionId(java.lang.String headrevisionid)
	{
		setHeadRevisionId(getContext(), headrevisionid);
	}

	/**
	 * Set value of HeadRevisionId
	 * @param context
	 * @param headrevisionid
	 */
	public final void setHeadRevisionId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String headrevisionid)
	{
		getMendixObject().setValue(context, MemberNames.HeadRevisionId.toString(), headrevisionid);
	}

	/**
	 * @return value of WebViewLink
	 */
	public final java.lang.String getWebViewLink()
	{
		return getWebViewLink(getContext());
	}

	/**
	 * @param context
	 * @return value of WebViewLink
	 */
	public final java.lang.String getWebViewLink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WebViewLink.toString());
	}

	/**
	 * Set value of WebViewLink
	 * @param webviewlink
	 */
	public final void setWebViewLink(java.lang.String webviewlink)
	{
		setWebViewLink(getContext(), webviewlink);
	}

	/**
	 * Set value of WebViewLink
	 * @param context
	 * @param webviewlink
	 */
	public final void setWebViewLink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String webviewlink)
	{
		getMendixObject().setValue(context, MemberNames.WebViewLink.toString(), webviewlink);
	}

	/**
	 * @return value of WebContentLink
	 */
	public final java.lang.String getWebContentLink()
	{
		return getWebContentLink(getContext());
	}

	/**
	 * @param context
	 * @return value of WebContentLink
	 */
	public final java.lang.String getWebContentLink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WebContentLink.toString());
	}

	/**
	 * Set value of WebContentLink
	 * @param webcontentlink
	 */
	public final void setWebContentLink(java.lang.String webcontentlink)
	{
		setWebContentLink(getContext(), webcontentlink);
	}

	/**
	 * Set value of WebContentLink
	 * @param context
	 * @param webcontentlink
	 */
	public final void setWebContentLink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String webcontentlink)
	{
		getMendixObject().setValue(context, MemberNames.WebContentLink.toString(), webcontentlink);
	}

	/**
	 * @return value of Size
	 */
	public final java.lang.String getSize()
	{
		return getSize(getContext());
	}

	/**
	 * @param context
	 * @return value of Size
	 */
	public final java.lang.String getSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Size.toString());
	}

	/**
	 * Set value of Size
	 * @param size
	 */
	public final void setSize(java.lang.String size)
	{
		setSize(getContext(), size);
	}

	/**
	 * Set value of Size
	 * @param context
	 * @param size
	 */
	public final void setSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String size)
	{
		getMendixObject().setValue(context, MemberNames.Size.toString(), size);
	}

	/**
	 * @return value of ViewersCanCopyContent
	 */
	public final java.lang.Boolean getViewersCanCopyContent()
	{
		return getViewersCanCopyContent(getContext());
	}

	/**
	 * @param context
	 * @return value of ViewersCanCopyContent
	 */
	public final java.lang.Boolean getViewersCanCopyContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ViewersCanCopyContent.toString());
	}

	/**
	 * Set value of ViewersCanCopyContent
	 * @param viewerscancopycontent
	 */
	public final void setViewersCanCopyContent(java.lang.Boolean viewerscancopycontent)
	{
		setViewersCanCopyContent(getContext(), viewerscancopycontent);
	}

	/**
	 * Set value of ViewersCanCopyContent
	 * @param context
	 * @param viewerscancopycontent
	 */
	public final void setViewersCanCopyContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean viewerscancopycontent)
	{
		getMendixObject().setValue(context, MemberNames.ViewersCanCopyContent.toString(), viewerscancopycontent);
	}

	/**
	 * @return value of HasThumbnail
	 */
	public final java.lang.Boolean getHasThumbnail()
	{
		return getHasThumbnail(getContext());
	}

	/**
	 * @param context
	 * @return value of HasThumbnail
	 */
	public final java.lang.Boolean getHasThumbnail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasThumbnail.toString());
	}

	/**
	 * Set value of HasThumbnail
	 * @param hasthumbnail
	 */
	public final void setHasThumbnail(java.lang.Boolean hasthumbnail)
	{
		setHasThumbnail(getContext(), hasthumbnail);
	}

	/**
	 * Set value of HasThumbnail
	 * @param context
	 * @param hasthumbnail
	 */
	public final void setHasThumbnail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasthumbnail)
	{
		getMendixObject().setValue(context, MemberNames.HasThumbnail.toString(), hasthumbnail);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Starred
	 */
	public final java.lang.Boolean getStarred()
	{
		return getStarred(getContext());
	}

	/**
	 * @param context
	 * @return value of Starred
	 */
	public final java.lang.Boolean getStarred(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Starred.toString());
	}

	/**
	 * Set value of Starred
	 * @param starred
	 */
	public final void setStarred(java.lang.Boolean starred)
	{
		setStarred(getContext(), starred);
	}

	/**
	 * Set value of Starred
	 * @param context
	 * @param starred
	 */
	public final void setStarred(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean starred)
	{
		getMendixObject().setValue(context, MemberNames.Starred.toString(), starred);
	}

	/**
	 * @return value of Trashed
	 */
	public final java.lang.Boolean getTrashed()
	{
		return getTrashed(getContext());
	}

	/**
	 * @param context
	 * @return value of Trashed
	 */
	public final java.lang.Boolean getTrashed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Trashed.toString());
	}

	/**
	 * Set value of Trashed
	 * @param trashed
	 */
	public final void setTrashed(java.lang.Boolean trashed)
	{
		setTrashed(getContext(), trashed);
	}

	/**
	 * Set value of Trashed
	 * @param context
	 * @param trashed
	 */
	public final void setTrashed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean trashed)
	{
		getMendixObject().setValue(context, MemberNames.Trashed.toString(), trashed);
	}

	/**
	 * @return value of ExplicitlyTrashed
	 */
	public final java.lang.Boolean getExplicitlyTrashed()
	{
		return getExplicitlyTrashed(getContext());
	}

	/**
	 * @param context
	 * @return value of ExplicitlyTrashed
	 */
	public final java.lang.Boolean getExplicitlyTrashed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ExplicitlyTrashed.toString());
	}

	/**
	 * Set value of ExplicitlyTrashed
	 * @param explicitlytrashed
	 */
	public final void setExplicitlyTrashed(java.lang.Boolean explicitlytrashed)
	{
		setExplicitlyTrashed(getContext(), explicitlytrashed);
	}

	/**
	 * Set value of ExplicitlyTrashed
	 * @param context
	 * @param explicitlytrashed
	 */
	public final void setExplicitlyTrashed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean explicitlytrashed)
	{
		getMendixObject().setValue(context, MemberNames.ExplicitlyTrashed.toString(), explicitlytrashed);
	}

	/**
	 * @return value of CreatedTime
	 */
	public final java.util.Date getCreatedTime()
	{
		return getCreatedTime(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedTime
	 */
	public final java.util.Date getCreatedTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreatedTime.toString());
	}

	/**
	 * Set value of CreatedTime
	 * @param createdtime
	 */
	public final void setCreatedTime(java.util.Date createdtime)
	{
		setCreatedTime(getContext(), createdtime);
	}

	/**
	 * Set value of CreatedTime
	 * @param context
	 * @param createdtime
	 */
	public final void setCreatedTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createdtime)
	{
		getMendixObject().setValue(context, MemberNames.CreatedTime.toString(), createdtime);
	}

	/**
	 * @return value of ModifiedTime
	 */
	public final java.util.Date getModifiedTime()
	{
		return getModifiedTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ModifiedTime
	 */
	public final java.util.Date getModifiedTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ModifiedTime.toString());
	}

	/**
	 * Set value of ModifiedTime
	 * @param modifiedtime
	 */
	public final void setModifiedTime(java.util.Date modifiedtime)
	{
		setModifiedTime(getContext(), modifiedtime);
	}

	/**
	 * Set value of ModifiedTime
	 * @param context
	 * @param modifiedtime
	 */
	public final void setModifiedTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date modifiedtime)
	{
		getMendixObject().setValue(context, MemberNames.ModifiedTime.toString(), modifiedtime);
	}

	/**
	 * @return value of ModifiedByMeTime
	 */
	public final java.util.Date getModifiedByMeTime()
	{
		return getModifiedByMeTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ModifiedByMeTime
	 */
	public final java.util.Date getModifiedByMeTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ModifiedByMeTime.toString());
	}

	/**
	 * Set value of ModifiedByMeTime
	 * @param modifiedbymetime
	 */
	public final void setModifiedByMeTime(java.util.Date modifiedbymetime)
	{
		setModifiedByMeTime(getContext(), modifiedbymetime);
	}

	/**
	 * Set value of ModifiedByMeTime
	 * @param context
	 * @param modifiedbymetime
	 */
	public final void setModifiedByMeTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date modifiedbymetime)
	{
		getMendixObject().setValue(context, MemberNames.ModifiedByMeTime.toString(), modifiedbymetime);
	}

	/**
	 * @return value of QuotaBytesUsed
	 */
	public final java.lang.String getQuotaBytesUsed()
	{
		return getQuotaBytesUsed(getContext());
	}

	/**
	 * @param context
	 * @return value of QuotaBytesUsed
	 */
	public final java.lang.String getQuotaBytesUsed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QuotaBytesUsed.toString());
	}

	/**
	 * Set value of QuotaBytesUsed
	 * @param quotabytesused
	 */
	public final void setQuotaBytesUsed(java.lang.String quotabytesused)
	{
		setQuotaBytesUsed(getContext(), quotabytesused);
	}

	/**
	 * Set value of QuotaBytesUsed
	 * @param context
	 * @param quotabytesused
	 */
	public final void setQuotaBytesUsed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String quotabytesused)
	{
		getMendixObject().setValue(context, MemberNames.QuotaBytesUsed.toString(), quotabytesused);
	}

	/**
	 * @return value of Version
	 */
	public final java.lang.String getVersion()
	{
		return getVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of Version
	 */
	public final java.lang.String getVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Version.toString());
	}

	/**
	 * Set value of Version
	 * @param version
	 */
	public final void setVersion(java.lang.String version)
	{
		setVersion(getContext(), version);
	}

	/**
	 * Set value of Version
	 * @param context
	 * @param version
	 */
	public final void setVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String version)
	{
		getMendixObject().setValue(context, MemberNames.Version.toString(), version);
	}

	/**
	 * @return value of OriginalFilename
	 */
	public final java.lang.String getOriginalFilename()
	{
		return getOriginalFilename(getContext());
	}

	/**
	 * @param context
	 * @return value of OriginalFilename
	 */
	public final java.lang.String getOriginalFilename(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OriginalFilename.toString());
	}

	/**
	 * Set value of OriginalFilename
	 * @param originalfilename
	 */
	public final void setOriginalFilename(java.lang.String originalfilename)
	{
		setOriginalFilename(getContext(), originalfilename);
	}

	/**
	 * Set value of OriginalFilename
	 * @param context
	 * @param originalfilename
	 */
	public final void setOriginalFilename(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String originalfilename)
	{
		getMendixObject().setValue(context, MemberNames.OriginalFilename.toString(), originalfilename);
	}

	/**
	 * @return value of OwnedByMe
	 */
	public final java.lang.Boolean getOwnedByMe()
	{
		return getOwnedByMe(getContext());
	}

	/**
	 * @param context
	 * @return value of OwnedByMe
	 */
	public final java.lang.Boolean getOwnedByMe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.OwnedByMe.toString());
	}

	/**
	 * Set value of OwnedByMe
	 * @param ownedbyme
	 */
	public final void setOwnedByMe(java.lang.Boolean ownedbyme)
	{
		setOwnedByMe(getContext(), ownedbyme);
	}

	/**
	 * Set value of OwnedByMe
	 * @param context
	 * @param ownedbyme
	 */
	public final void setOwnedByMe(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ownedbyme)
	{
		getMendixObject().setValue(context, MemberNames.OwnedByMe.toString(), ownedbyme);
	}

	/**
	 * @return value of FullFileExtension
	 */
	public final java.lang.String getFullFileExtension()
	{
		return getFullFileExtension(getContext());
	}

	/**
	 * @param context
	 * @return value of FullFileExtension
	 */
	public final java.lang.String getFullFileExtension(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FullFileExtension.toString());
	}

	/**
	 * Set value of FullFileExtension
	 * @param fullfileextension
	 */
	public final void setFullFileExtension(java.lang.String fullfileextension)
	{
		setFullFileExtension(getContext(), fullfileextension);
	}

	/**
	 * Set value of FullFileExtension
	 * @param context
	 * @param fullfileextension
	 */
	public final void setFullFileExtension(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fullfileextension)
	{
		getMendixObject().setValue(context, MemberNames.FullFileExtension.toString(), fullfileextension);
	}

	/**
	 * @return value of IsAppAuthorized
	 */
	public final java.lang.Boolean getIsAppAuthorized()
	{
		return getIsAppAuthorized(getContext());
	}

	/**
	 * @param context
	 * @return value of IsAppAuthorized
	 */
	public final java.lang.Boolean getIsAppAuthorized(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsAppAuthorized.toString());
	}

	/**
	 * Set value of IsAppAuthorized
	 * @param isappauthorized
	 */
	public final void setIsAppAuthorized(java.lang.Boolean isappauthorized)
	{
		setIsAppAuthorized(getContext(), isappauthorized);
	}

	/**
	 * Set value of IsAppAuthorized
	 * @param context
	 * @param isappauthorized
	 */
	public final void setIsAppAuthorized(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isappauthorized)
	{
		getMendixObject().setValue(context, MemberNames.IsAppAuthorized.toString(), isappauthorized);
	}

	/**
	 * @return value of ThumbnailVersion
	 */
	public final java.lang.String getThumbnailVersion()
	{
		return getThumbnailVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of ThumbnailVersion
	 */
	public final java.lang.String getThumbnailVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ThumbnailVersion.toString());
	}

	/**
	 * Set value of ThumbnailVersion
	 * @param thumbnailversion
	 */
	public final void setThumbnailVersion(java.lang.String thumbnailversion)
	{
		setThumbnailVersion(getContext(), thumbnailversion);
	}

	/**
	 * Set value of ThumbnailVersion
	 * @param context
	 * @param thumbnailversion
	 */
	public final void setThumbnailVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String thumbnailversion)
	{
		getMendixObject().setValue(context, MemberNames.ThumbnailVersion.toString(), thumbnailversion);
	}

	/**
	 * @return value of ModifiedByMe
	 */
	public final java.lang.Boolean getModifiedByMe()
	{
		return getModifiedByMe(getContext());
	}

	/**
	 * @param context
	 * @return value of ModifiedByMe
	 */
	public final java.lang.Boolean getModifiedByMe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ModifiedByMe.toString());
	}

	/**
	 * Set value of ModifiedByMe
	 * @param modifiedbyme
	 */
	public final void setModifiedByMe(java.lang.Boolean modifiedbyme)
	{
		setModifiedByMe(getContext(), modifiedbyme);
	}

	/**
	 * Set value of ModifiedByMe
	 * @param context
	 * @param modifiedbyme
	 */
	public final void setModifiedByMe(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean modifiedbyme)
	{
		getMendixObject().setValue(context, MemberNames.ModifiedByMe.toString(), modifiedbyme);
	}

	/**
	 * @return value of Sha1Checksum
	 */
	public final java.lang.String getSha1Checksum()
	{
		return getSha1Checksum(getContext());
	}

	/**
	 * @param context
	 * @return value of Sha1Checksum
	 */
	public final java.lang.String getSha1Checksum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sha1Checksum.toString());
	}

	/**
	 * Set value of Sha1Checksum
	 * @param sha1checksum
	 */
	public final void setSha1Checksum(java.lang.String sha1checksum)
	{
		setSha1Checksum(getContext(), sha1checksum);
	}

	/**
	 * Set value of Sha1Checksum
	 * @param context
	 * @param sha1checksum
	 */
	public final void setSha1Checksum(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sha1checksum)
	{
		getMendixObject().setValue(context, MemberNames.Sha1Checksum.toString(), sha1checksum);
	}

	/**
	 * @return value of Sha256Checksum
	 */
	public final java.lang.String getSha256Checksum()
	{
		return getSha256Checksum(getContext());
	}

	/**
	 * @param context
	 * @return value of Sha256Checksum
	 */
	public final java.lang.String getSha256Checksum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sha256Checksum.toString());
	}

	/**
	 * Set value of Sha256Checksum
	 * @param sha256checksum
	 */
	public final void setSha256Checksum(java.lang.String sha256checksum)
	{
		setSha256Checksum(getContext(), sha256checksum);
	}

	/**
	 * Set value of Sha256Checksum
	 * @param context
	 * @param sha256checksum
	 */
	public final void setSha256Checksum(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sha256checksum)
	{
		getMendixObject().setValue(context, MemberNames.Sha256Checksum.toString(), sha256checksum);
	}

	/**
	 * @return value of ViewedByMeTime
	 */
	public final java.util.Date getViewedByMeTime()
	{
		return getViewedByMeTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ViewedByMeTime
	 */
	public final java.util.Date getViewedByMeTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ViewedByMeTime.toString());
	}

	/**
	 * Set value of ViewedByMeTime
	 * @param viewedbymetime
	 */
	public final void setViewedByMeTime(java.util.Date viewedbymetime)
	{
		setViewedByMeTime(getContext(), viewedbymetime);
	}

	/**
	 * Set value of ViewedByMeTime
	 * @param context
	 * @param viewedbymetime
	 */
	public final void setViewedByMeTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date viewedbymetime)
	{
		getMendixObject().setValue(context, MemberNames.ViewedByMeTime.toString(), viewedbymetime);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GoogleDriveFile_FilesList
	 */
	public final googledriveconnector.proxies.FilesList getGoogleDriveFile_FilesList() throws com.mendix.core.CoreException
	{
		return getGoogleDriveFile_FilesList(getContext());
	}

	/**
	 * @param context
	 * @return value of GoogleDriveFile_FilesList
	 * @throws com.mendix.core.CoreException
	 */
	public final googledriveconnector.proxies.FilesList getGoogleDriveFile_FilesList(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googledriveconnector.proxies.FilesList result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GoogleDriveFile_FilesList.toString());
		if (identifier != null) {
			result = googledriveconnector.proxies.FilesList.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of GoogleDriveFile_FilesList
	 * @param googledrivefile_fileslist
	 */
	public final void setGoogleDriveFile_FilesList(googledriveconnector.proxies.FilesList googledrivefile_fileslist)
	{
		setGoogleDriveFile_FilesList(getContext(), googledrivefile_fileslist);
	}

	/**
	 * Set value of GoogleDriveFile_FilesList
	 * @param context
	 * @param googledrivefile_fileslist
	 */
	public final void setGoogleDriveFile_FilesList(com.mendix.systemwideinterfaces.core.IContext context, googledriveconnector.proxies.FilesList googledrivefile_fileslist)
	{
		if (googledrivefile_fileslist == null) {
			getMendixObject().setValue(context, MemberNames.GoogleDriveFile_FilesList.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.GoogleDriveFile_FilesList.toString(), googledrivefile_fileslist.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parents_GoogleDriveFile
	 */
	public final googledriveconnector.proxies.Parents getParents_GoogleDriveFile() throws com.mendix.core.CoreException
	{
		return getParents_GoogleDriveFile(getContext());
	}

	/**
	 * @param context
	 * @return value of Parents_GoogleDriveFile
	 * @throws com.mendix.core.CoreException
	 */
	public final googledriveconnector.proxies.Parents getParents_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googledriveconnector.proxies.Parents result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parents_GoogleDriveFile.toString());
		if (identifier != null) {
			result = googledriveconnector.proxies.Parents.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parents_GoogleDriveFile
	 * @param parents_googledrivefile
	 */
	public final void setParents_GoogleDriveFile(googledriveconnector.proxies.Parents parents_googledrivefile)
	{
		setParents_GoogleDriveFile(getContext(), parents_googledrivefile);
	}

	/**
	 * Set value of Parents_GoogleDriveFile
	 * @param context
	 * @param parents_googledrivefile
	 */
	public final void setParents_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context, googledriveconnector.proxies.Parents parents_googledrivefile)
	{
		if (parents_googledrivefile == null) {
			getMendixObject().setValue(context, MemberNames.Parents_GoogleDriveFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parents_GoogleDriveFile.toString(), parents_googledrivefile.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of LastModifyingUser_GoogleDriveFile
	 */
	public final googledriveconnector.proxies.LastModifyingUser getLastModifyingUser_GoogleDriveFile() throws com.mendix.core.CoreException
	{
		return getLastModifyingUser_GoogleDriveFile(getContext());
	}

	/**
	 * @param context
	 * @return value of LastModifyingUser_GoogleDriveFile
	 * @throws com.mendix.core.CoreException
	 */
	public final googledriveconnector.proxies.LastModifyingUser getLastModifyingUser_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googledriveconnector.proxies.LastModifyingUser result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.LastModifyingUser_GoogleDriveFile.toString());
		if (identifier != null) {
			result = googledriveconnector.proxies.LastModifyingUser.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of LastModifyingUser_GoogleDriveFile
	 * @param lastmodifyinguser_googledrivefile
	 */
	public final void setLastModifyingUser_GoogleDriveFile(googledriveconnector.proxies.LastModifyingUser lastmodifyinguser_googledrivefile)
	{
		setLastModifyingUser_GoogleDriveFile(getContext(), lastmodifyinguser_googledrivefile);
	}

	/**
	 * Set value of LastModifyingUser_GoogleDriveFile
	 * @param context
	 * @param lastmodifyinguser_googledrivefile
	 */
	public final void setLastModifyingUser_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context, googledriveconnector.proxies.LastModifyingUser lastmodifyinguser_googledrivefile)
	{
		if (lastmodifyinguser_googledrivefile == null) {
			getMendixObject().setValue(context, MemberNames.LastModifyingUser_GoogleDriveFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.LastModifyingUser_GoogleDriveFile.toString(), lastmodifyinguser_googledrivefile.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Owners_GoogleDriveFile
	 */
	public final googledriveconnector.proxies.Owners getOwners_GoogleDriveFile() throws com.mendix.core.CoreException
	{
		return getOwners_GoogleDriveFile(getContext());
	}

	/**
	 * @param context
	 * @return value of Owners_GoogleDriveFile
	 * @throws com.mendix.core.CoreException
	 */
	public final googledriveconnector.proxies.Owners getOwners_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googledriveconnector.proxies.Owners result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Owners_GoogleDriveFile.toString());
		if (identifier != null) {
			result = googledriveconnector.proxies.Owners.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Owners_GoogleDriveFile
	 * @param owners_googledrivefile
	 */
	public final void setOwners_GoogleDriveFile(googledriveconnector.proxies.Owners owners_googledrivefile)
	{
		setOwners_GoogleDriveFile(getContext(), owners_googledrivefile);
	}

	/**
	 * Set value of Owners_GoogleDriveFile
	 * @param context
	 * @param owners_googledrivefile
	 */
	public final void setOwners_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context, googledriveconnector.proxies.Owners owners_googledrivefile)
	{
		if (owners_googledrivefile == null) {
			getMendixObject().setValue(context, MemberNames.Owners_GoogleDriveFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Owners_GoogleDriveFile.toString(), owners_googledrivefile.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Permissions_GoogleDriveFile
	 */
	public final googledriveconnector.proxies.Permissions getPermissions_GoogleDriveFile() throws com.mendix.core.CoreException
	{
		return getPermissions_GoogleDriveFile(getContext());
	}

	/**
	 * @param context
	 * @return value of Permissions_GoogleDriveFile
	 * @throws com.mendix.core.CoreException
	 */
	public final googledriveconnector.proxies.Permissions getPermissions_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googledriveconnector.proxies.Permissions result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Permissions_GoogleDriveFile.toString());
		if (identifier != null) {
			result = googledriveconnector.proxies.Permissions.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Permissions_GoogleDriveFile
	 * @param permissions_googledrivefile
	 */
	public final void setPermissions_GoogleDriveFile(googledriveconnector.proxies.Permissions permissions_googledrivefile)
	{
		setPermissions_GoogleDriveFile(getContext(), permissions_googledrivefile);
	}

	/**
	 * Set value of Permissions_GoogleDriveFile
	 * @param context
	 * @param permissions_googledrivefile
	 */
	public final void setPermissions_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context, googledriveconnector.proxies.Permissions permissions_googledrivefile)
	{
		if (permissions_googledrivefile == null) {
			getMendixObject().setValue(context, MemberNames.Permissions_GoogleDriveFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Permissions_GoogleDriveFile.toString(), permissions_googledrivefile.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Spaces_GoogleDriveFile
	 */
	public final googledriveconnector.proxies.Spaces getSpaces_GoogleDriveFile() throws com.mendix.core.CoreException
	{
		return getSpaces_GoogleDriveFile(getContext());
	}

	/**
	 * @param context
	 * @return value of Spaces_GoogleDriveFile
	 * @throws com.mendix.core.CoreException
	 */
	public final googledriveconnector.proxies.Spaces getSpaces_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googledriveconnector.proxies.Spaces result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Spaces_GoogleDriveFile.toString());
		if (identifier != null) {
			result = googledriveconnector.proxies.Spaces.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Spaces_GoogleDriveFile
	 * @param spaces_googledrivefile
	 */
	public final void setSpaces_GoogleDriveFile(googledriveconnector.proxies.Spaces spaces_googledrivefile)
	{
		setSpaces_GoogleDriveFile(getContext(), spaces_googledrivefile);
	}

	/**
	 * Set value of Spaces_GoogleDriveFile
	 * @param context
	 * @param spaces_googledrivefile
	 */
	public final void setSpaces_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context, googledriveconnector.proxies.Spaces spaces_googledrivefile)
	{
		if (spaces_googledrivefile == null) {
			getMendixObject().setValue(context, MemberNames.Spaces_GoogleDriveFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Spaces_GoogleDriveFile.toString(), spaces_googledrivefile.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Capabilities_GoogleDriveFile
	 */
	public final googledriveconnector.proxies.Capabilities getCapabilities_GoogleDriveFile() throws com.mendix.core.CoreException
	{
		return getCapabilities_GoogleDriveFile(getContext());
	}

	/**
	 * @param context
	 * @return value of Capabilities_GoogleDriveFile
	 * @throws com.mendix.core.CoreException
	 */
	public final googledriveconnector.proxies.Capabilities getCapabilities_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googledriveconnector.proxies.Capabilities result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Capabilities_GoogleDriveFile.toString());
		if (identifier != null) {
			result = googledriveconnector.proxies.Capabilities.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Capabilities_GoogleDriveFile
	 * @param capabilities_googledrivefile
	 */
	public final void setCapabilities_GoogleDriveFile(googledriveconnector.proxies.Capabilities capabilities_googledrivefile)
	{
		setCapabilities_GoogleDriveFile(getContext(), capabilities_googledrivefile);
	}

	/**
	 * Set value of Capabilities_GoogleDriveFile
	 * @param context
	 * @param capabilities_googledrivefile
	 */
	public final void setCapabilities_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context, googledriveconnector.proxies.Capabilities capabilities_googledrivefile)
	{
		if (capabilities_googledrivefile == null) {
			getMendixObject().setValue(context, MemberNames.Capabilities_GoogleDriveFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Capabilities_GoogleDriveFile.toString(), capabilities_googledrivefile.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PermissionIds_GoogleDriveFile
	 */
	public final googledriveconnector.proxies.PermissionIds getPermissionIds_GoogleDriveFile() throws com.mendix.core.CoreException
	{
		return getPermissionIds_GoogleDriveFile(getContext());
	}

	/**
	 * @param context
	 * @return value of PermissionIds_GoogleDriveFile
	 * @throws com.mendix.core.CoreException
	 */
	public final googledriveconnector.proxies.PermissionIds getPermissionIds_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googledriveconnector.proxies.PermissionIds result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PermissionIds_GoogleDriveFile.toString());
		if (identifier != null) {
			result = googledriveconnector.proxies.PermissionIds.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PermissionIds_GoogleDriveFile
	 * @param permissionids_googledrivefile
	 */
	public final void setPermissionIds_GoogleDriveFile(googledriveconnector.proxies.PermissionIds permissionids_googledrivefile)
	{
		setPermissionIds_GoogleDriveFile(getContext(), permissionids_googledrivefile);
	}

	/**
	 * Set value of PermissionIds_GoogleDriveFile
	 * @param context
	 * @param permissionids_googledrivefile
	 */
	public final void setPermissionIds_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context, googledriveconnector.proxies.PermissionIds permissionids_googledrivefile)
	{
		if (permissionids_googledrivefile == null) {
			getMendixObject().setValue(context, MemberNames.PermissionIds_GoogleDriveFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PermissionIds_GoogleDriveFile.toString(), permissionids_googledrivefile.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of LinkShareMetadata_GoogleDriveFile
	 */
	public final googledriveconnector.proxies.LinkShareMetadata getLinkShareMetadata_GoogleDriveFile() throws com.mendix.core.CoreException
	{
		return getLinkShareMetadata_GoogleDriveFile(getContext());
	}

	/**
	 * @param context
	 * @return value of LinkShareMetadata_GoogleDriveFile
	 * @throws com.mendix.core.CoreException
	 */
	public final googledriveconnector.proxies.LinkShareMetadata getLinkShareMetadata_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googledriveconnector.proxies.LinkShareMetadata result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.LinkShareMetadata_GoogleDriveFile.toString());
		if (identifier != null) {
			result = googledriveconnector.proxies.LinkShareMetadata.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of LinkShareMetadata_GoogleDriveFile
	 * @param linksharemetadata_googledrivefile
	 */
	public final void setLinkShareMetadata_GoogleDriveFile(googledriveconnector.proxies.LinkShareMetadata linksharemetadata_googledrivefile)
	{
		setLinkShareMetadata_GoogleDriveFile(getContext(), linksharemetadata_googledrivefile);
	}

	/**
	 * Set value of LinkShareMetadata_GoogleDriveFile
	 * @param context
	 * @param linksharemetadata_googledrivefile
	 */
	public final void setLinkShareMetadata_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context, googledriveconnector.proxies.LinkShareMetadata linksharemetadata_googledrivefile)
	{
		if (linksharemetadata_googledrivefile == null) {
			getMendixObject().setValue(context, MemberNames.LinkShareMetadata_GoogleDriveFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.LinkShareMetadata_GoogleDriveFile.toString(), linksharemetadata_googledrivefile.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return googleDriveFileMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final googledriveconnector.proxies.GoogleDriveFile that = (googledriveconnector.proxies.GoogleDriveFile) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
