// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googledriveconnector.proxies;

public class GoogleDriveListRoot
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject googleDriveListRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GoogleDriveConnector.GoogleDriveListRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NextPageToken("NextPageToken"),
		Kind("Kind"),
		IncompleteSearch("IncompleteSearch"),
		FilesList_GoogleDriveListRoot("GoogleDriveConnector.FilesList_GoogleDriveListRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GoogleDriveListRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected GoogleDriveListRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject googleDriveListRootMendixObject)
	{
		if (googleDriveListRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, googleDriveListRootMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.googleDriveListRootMendixObject = googleDriveListRootMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GoogleDriveListRoot.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static googledriveconnector.proxies.GoogleDriveListRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return googledriveconnector.proxies.GoogleDriveListRoot.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static googledriveconnector.proxies.GoogleDriveListRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new googledriveconnector.proxies.GoogleDriveListRoot(context, mendixObject);
	}

	public static googledriveconnector.proxies.GoogleDriveListRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return googledriveconnector.proxies.GoogleDriveListRoot.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NextPageToken
	 */
	public final java.lang.String getNextPageToken()
	{
		return getNextPageToken(getContext());
	}

	/**
	 * @param context
	 * @return value of NextPageToken
	 */
	public final java.lang.String getNextPageToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NextPageToken.toString());
	}

	/**
	 * Set value of NextPageToken
	 * @param nextpagetoken
	 */
	public final void setNextPageToken(java.lang.String nextpagetoken)
	{
		setNextPageToken(getContext(), nextpagetoken);
	}

	/**
	 * Set value of NextPageToken
	 * @param context
	 * @param nextpagetoken
	 */
	public final void setNextPageToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nextpagetoken)
	{
		getMendixObject().setValue(context, MemberNames.NextPageToken.toString(), nextpagetoken);
	}

	/**
	 * @return value of Kind
	 */
	public final java.lang.String getKind()
	{
		return getKind(getContext());
	}

	/**
	 * @param context
	 * @return value of Kind
	 */
	public final java.lang.String getKind(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Kind.toString());
	}

	/**
	 * Set value of Kind
	 * @param kind
	 */
	public final void setKind(java.lang.String kind)
	{
		setKind(getContext(), kind);
	}

	/**
	 * Set value of Kind
	 * @param context
	 * @param kind
	 */
	public final void setKind(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kind)
	{
		getMendixObject().setValue(context, MemberNames.Kind.toString(), kind);
	}

	/**
	 * @return value of IncompleteSearch
	 */
	public final java.lang.Boolean getIncompleteSearch()
	{
		return getIncompleteSearch(getContext());
	}

	/**
	 * @param context
	 * @return value of IncompleteSearch
	 */
	public final java.lang.Boolean getIncompleteSearch(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IncompleteSearch.toString());
	}

	/**
	 * Set value of IncompleteSearch
	 * @param incompletesearch
	 */
	public final void setIncompleteSearch(java.lang.Boolean incompletesearch)
	{
		setIncompleteSearch(getContext(), incompletesearch);
	}

	/**
	 * Set value of IncompleteSearch
	 * @param context
	 * @param incompletesearch
	 */
	public final void setIncompleteSearch(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean incompletesearch)
	{
		getMendixObject().setValue(context, MemberNames.IncompleteSearch.toString(), incompletesearch);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FilesList_GoogleDriveListRoot
	 */
	public final googledriveconnector.proxies.FilesList getFilesList_GoogleDriveListRoot() throws com.mendix.core.CoreException
	{
		return getFilesList_GoogleDriveListRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of FilesList_GoogleDriveListRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final googledriveconnector.proxies.FilesList getFilesList_GoogleDriveListRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googledriveconnector.proxies.FilesList result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FilesList_GoogleDriveListRoot.toString());
		if (identifier != null) {
			result = googledriveconnector.proxies.FilesList.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FilesList_GoogleDriveListRoot
	 * @param fileslist_googledrivelistroot
	 */
	public final void setFilesList_GoogleDriveListRoot(googledriveconnector.proxies.FilesList fileslist_googledrivelistroot)
	{
		setFilesList_GoogleDriveListRoot(getContext(), fileslist_googledrivelistroot);
	}

	/**
	 * Set value of FilesList_GoogleDriveListRoot
	 * @param context
	 * @param fileslist_googledrivelistroot
	 */
	public final void setFilesList_GoogleDriveListRoot(com.mendix.systemwideinterfaces.core.IContext context, googledriveconnector.proxies.FilesList fileslist_googledrivelistroot)
	{
		if (fileslist_googledrivelistroot == null) {
			getMendixObject().setValue(context, MemberNames.FilesList_GoogleDriveListRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FilesList_GoogleDriveListRoot.toString(), fileslist_googledrivelistroot.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return googleDriveListRootMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final googledriveconnector.proxies.GoogleDriveListRoot that = (googledriveconnector.proxies.GoogleDriveListRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
