// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googledriveconnector.proxies;

public class GoogleDrivePermission
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject googleDrivePermissionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GoogleDriveConnector.GoogleDrivePermission";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		DisplayName("DisplayName"),
		_type("_type"),
		Kind("Kind"),
		PhotoLink("PhotoLink"),
		EmailAddress("EmailAddress"),
		Role("Role"),
		Deleted("Deleted"),
		PendingOwner("PendingOwner"),
		GoogleDrivePermission_Permissions("GoogleDriveConnector.GoogleDrivePermission_Permissions");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GoogleDrivePermission(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected GoogleDrivePermission(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject googleDrivePermissionMendixObject)
	{
		if (googleDrivePermissionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, googleDrivePermissionMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.googleDrivePermissionMendixObject = googleDrivePermissionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GoogleDrivePermission.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static googledriveconnector.proxies.GoogleDrivePermission initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return googledriveconnector.proxies.GoogleDrivePermission.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static googledriveconnector.proxies.GoogleDrivePermission initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new googledriveconnector.proxies.GoogleDrivePermission(context, mendixObject);
	}

	public static googledriveconnector.proxies.GoogleDrivePermission load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return googledriveconnector.proxies.GoogleDrivePermission.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of _type
	 */
	public final java.lang.String get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final java.lang.String get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(java.lang.String _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return value of Kind
	 */
	public final java.lang.String getKind()
	{
		return getKind(getContext());
	}

	/**
	 * @param context
	 * @return value of Kind
	 */
	public final java.lang.String getKind(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Kind.toString());
	}

	/**
	 * Set value of Kind
	 * @param kind
	 */
	public final void setKind(java.lang.String kind)
	{
		setKind(getContext(), kind);
	}

	/**
	 * Set value of Kind
	 * @param context
	 * @param kind
	 */
	public final void setKind(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kind)
	{
		getMendixObject().setValue(context, MemberNames.Kind.toString(), kind);
	}

	/**
	 * @return value of PhotoLink
	 */
	public final java.lang.String getPhotoLink()
	{
		return getPhotoLink(getContext());
	}

	/**
	 * @param context
	 * @return value of PhotoLink
	 */
	public final java.lang.String getPhotoLink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PhotoLink.toString());
	}

	/**
	 * Set value of PhotoLink
	 * @param photolink
	 */
	public final void setPhotoLink(java.lang.String photolink)
	{
		setPhotoLink(getContext(), photolink);
	}

	/**
	 * Set value of PhotoLink
	 * @param context
	 * @param photolink
	 */
	public final void setPhotoLink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String photolink)
	{
		getMendixObject().setValue(context, MemberNames.PhotoLink.toString(), photolink);
	}

	/**
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress()
	{
		return getEmailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailAddress.toString());
	}

	/**
	 * Set value of EmailAddress
	 * @param emailaddress
	 */
	public final void setEmailAddress(java.lang.String emailaddress)
	{
		setEmailAddress(getContext(), emailaddress);
	}

	/**
	 * Set value of EmailAddress
	 * @param context
	 * @param emailaddress
	 */
	public final void setEmailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailaddress)
	{
		getMendixObject().setValue(context, MemberNames.EmailAddress.toString(), emailaddress);
	}

	/**
	 * @return value of Role
	 */
	public final java.lang.String getRole()
	{
		return getRole(getContext());
	}

	/**
	 * @param context
	 * @return value of Role
	 */
	public final java.lang.String getRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Role.toString());
	}

	/**
	 * Set value of Role
	 * @param role
	 */
	public final void setRole(java.lang.String role)
	{
		setRole(getContext(), role);
	}

	/**
	 * Set value of Role
	 * @param context
	 * @param role
	 */
	public final void setRole(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String role)
	{
		getMendixObject().setValue(context, MemberNames.Role.toString(), role);
	}

	/**
	 * @return value of Deleted
	 */
	public final java.lang.Boolean getDeleted()
	{
		return getDeleted(getContext());
	}

	/**
	 * @param context
	 * @return value of Deleted
	 */
	public final java.lang.Boolean getDeleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Deleted.toString());
	}

	/**
	 * Set value of Deleted
	 * @param deleted
	 */
	public final void setDeleted(java.lang.Boolean deleted)
	{
		setDeleted(getContext(), deleted);
	}

	/**
	 * Set value of Deleted
	 * @param context
	 * @param deleted
	 */
	public final void setDeleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean deleted)
	{
		getMendixObject().setValue(context, MemberNames.Deleted.toString(), deleted);
	}

	/**
	 * @return value of PendingOwner
	 */
	public final java.lang.Boolean getPendingOwner()
	{
		return getPendingOwner(getContext());
	}

	/**
	 * @param context
	 * @return value of PendingOwner
	 */
	public final java.lang.Boolean getPendingOwner(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PendingOwner.toString());
	}

	/**
	 * Set value of PendingOwner
	 * @param pendingowner
	 */
	public final void setPendingOwner(java.lang.Boolean pendingowner)
	{
		setPendingOwner(getContext(), pendingowner);
	}

	/**
	 * Set value of PendingOwner
	 * @param context
	 * @param pendingowner
	 */
	public final void setPendingOwner(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean pendingowner)
	{
		getMendixObject().setValue(context, MemberNames.PendingOwner.toString(), pendingowner);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GoogleDrivePermission_Permissions
	 */
	public final googledriveconnector.proxies.Permissions getGoogleDrivePermission_Permissions() throws com.mendix.core.CoreException
	{
		return getGoogleDrivePermission_Permissions(getContext());
	}

	/**
	 * @param context
	 * @return value of GoogleDrivePermission_Permissions
	 * @throws com.mendix.core.CoreException
	 */
	public final googledriveconnector.proxies.Permissions getGoogleDrivePermission_Permissions(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googledriveconnector.proxies.Permissions result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GoogleDrivePermission_Permissions.toString());
		if (identifier != null) {
			result = googledriveconnector.proxies.Permissions.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of GoogleDrivePermission_Permissions
	 * @param googledrivepermission_permissions
	 */
	public final void setGoogleDrivePermission_Permissions(googledriveconnector.proxies.Permissions googledrivepermission_permissions)
	{
		setGoogleDrivePermission_Permissions(getContext(), googledrivepermission_permissions);
	}

	/**
	 * Set value of GoogleDrivePermission_Permissions
	 * @param context
	 * @param googledrivepermission_permissions
	 */
	public final void setGoogleDrivePermission_Permissions(com.mendix.systemwideinterfaces.core.IContext context, googledriveconnector.proxies.Permissions googledrivepermission_permissions)
	{
		if (googledrivepermission_permissions == null) {
			getMendixObject().setValue(context, MemberNames.GoogleDrivePermission_Permissions.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.GoogleDrivePermission_Permissions.toString(), googledrivepermission_permissions.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return googleDrivePermissionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final googledriveconnector.proxies.GoogleDrivePermission that = (googledriveconnector.proxies.GoogleDrivePermission) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
