// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googledriveconnector.proxies;

public class LastModifyingUser
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject lastModifyingUserMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GoogleDriveConnector.LastModifyingUser";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisplayName("DisplayName"),
		Kind("Kind"),
		Me("Me"),
		PermissionId("PermissionId"),
		EmailAddress("EmailAddress"),
		PhotoLink("PhotoLink"),
		LastModifyingUser_GoogleDriveFile("GoogleDriveConnector.LastModifyingUser_GoogleDriveFile");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public LastModifyingUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected LastModifyingUser(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject lastModifyingUserMendixObject)
	{
		if (lastModifyingUserMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, lastModifyingUserMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.lastModifyingUserMendixObject = lastModifyingUserMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'LastModifyingUser.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static googledriveconnector.proxies.LastModifyingUser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return googledriveconnector.proxies.LastModifyingUser.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static googledriveconnector.proxies.LastModifyingUser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new googledriveconnector.proxies.LastModifyingUser(context, mendixObject);
	}

	public static googledriveconnector.proxies.LastModifyingUser load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return googledriveconnector.proxies.LastModifyingUser.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of Kind
	 */
	public final java.lang.String getKind()
	{
		return getKind(getContext());
	}

	/**
	 * @param context
	 * @return value of Kind
	 */
	public final java.lang.String getKind(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Kind.toString());
	}

	/**
	 * Set value of Kind
	 * @param kind
	 */
	public final void setKind(java.lang.String kind)
	{
		setKind(getContext(), kind);
	}

	/**
	 * Set value of Kind
	 * @param context
	 * @param kind
	 */
	public final void setKind(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kind)
	{
		getMendixObject().setValue(context, MemberNames.Kind.toString(), kind);
	}

	/**
	 * @return value of Me
	 */
	public final java.lang.Boolean getMe()
	{
		return getMe(getContext());
	}

	/**
	 * @param context
	 * @return value of Me
	 */
	public final java.lang.Boolean getMe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Me.toString());
	}

	/**
	 * Set value of Me
	 * @param me
	 */
	public final void setMe(java.lang.Boolean me)
	{
		setMe(getContext(), me);
	}

	/**
	 * Set value of Me
	 * @param context
	 * @param me
	 */
	public final void setMe(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean me)
	{
		getMendixObject().setValue(context, MemberNames.Me.toString(), me);
	}

	/**
	 * @return value of PermissionId
	 */
	public final java.lang.String getPermissionId()
	{
		return getPermissionId(getContext());
	}

	/**
	 * @param context
	 * @return value of PermissionId
	 */
	public final java.lang.String getPermissionId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PermissionId.toString());
	}

	/**
	 * Set value of PermissionId
	 * @param permissionid
	 */
	public final void setPermissionId(java.lang.String permissionid)
	{
		setPermissionId(getContext(), permissionid);
	}

	/**
	 * Set value of PermissionId
	 * @param context
	 * @param permissionid
	 */
	public final void setPermissionId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String permissionid)
	{
		getMendixObject().setValue(context, MemberNames.PermissionId.toString(), permissionid);
	}

	/**
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress()
	{
		return getEmailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailAddress.toString());
	}

	/**
	 * Set value of EmailAddress
	 * @param emailaddress
	 */
	public final void setEmailAddress(java.lang.String emailaddress)
	{
		setEmailAddress(getContext(), emailaddress);
	}

	/**
	 * Set value of EmailAddress
	 * @param context
	 * @param emailaddress
	 */
	public final void setEmailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailaddress)
	{
		getMendixObject().setValue(context, MemberNames.EmailAddress.toString(), emailaddress);
	}

	/**
	 * @return value of PhotoLink
	 */
	public final java.lang.String getPhotoLink()
	{
		return getPhotoLink(getContext());
	}

	/**
	 * @param context
	 * @return value of PhotoLink
	 */
	public final java.lang.String getPhotoLink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PhotoLink.toString());
	}

	/**
	 * Set value of PhotoLink
	 * @param photolink
	 */
	public final void setPhotoLink(java.lang.String photolink)
	{
		setPhotoLink(getContext(), photolink);
	}

	/**
	 * Set value of PhotoLink
	 * @param context
	 * @param photolink
	 */
	public final void setPhotoLink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String photolink)
	{
		getMendixObject().setValue(context, MemberNames.PhotoLink.toString(), photolink);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of LastModifyingUser_GoogleDriveFile
	 */
	public final googledriveconnector.proxies.GoogleDriveFile getLastModifyingUser_GoogleDriveFile() throws com.mendix.core.CoreException
	{
		return getLastModifyingUser_GoogleDriveFile(getContext());
	}

	/**
	 * @param context
	 * @return value of LastModifyingUser_GoogleDriveFile
	 * @throws com.mendix.core.CoreException
	 */
	public final googledriveconnector.proxies.GoogleDriveFile getLastModifyingUser_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googledriveconnector.proxies.GoogleDriveFile result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.LastModifyingUser_GoogleDriveFile.toString());
		if (identifier != null) {
			result = googledriveconnector.proxies.GoogleDriveFile.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of LastModifyingUser_GoogleDriveFile
	 * @param lastmodifyinguser_googledrivefile
	 */
	public final void setLastModifyingUser_GoogleDriveFile(googledriveconnector.proxies.GoogleDriveFile lastmodifyinguser_googledrivefile)
	{
		setLastModifyingUser_GoogleDriveFile(getContext(), lastmodifyinguser_googledrivefile);
	}

	/**
	 * Set value of LastModifyingUser_GoogleDriveFile
	 * @param context
	 * @param lastmodifyinguser_googledrivefile
	 */
	public final void setLastModifyingUser_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context, googledriveconnector.proxies.GoogleDriveFile lastmodifyinguser_googledrivefile)
	{
		if (lastmodifyinguser_googledrivefile == null) {
			getMendixObject().setValue(context, MemberNames.LastModifyingUser_GoogleDriveFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.LastModifyingUser_GoogleDriveFile.toString(), lastmodifyinguser_googledrivefile.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return lastModifyingUserMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final googledriveconnector.proxies.LastModifyingUser that = (googledriveconnector.proxies.LastModifyingUser) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
