// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googledriveconnector.proxies;

public class LinkShareMetadata
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject linkShareMetadataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GoogleDriveConnector.LinkShareMetadata";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SecurityUpdateEligible("SecurityUpdateEligible"),
		SecurityUpdateEnabled("SecurityUpdateEnabled"),
		LinkShareMetadata_GoogleDriveFile("GoogleDriveConnector.LinkShareMetadata_GoogleDriveFile");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public LinkShareMetadata(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected LinkShareMetadata(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject linkShareMetadataMendixObject)
	{
		if (linkShareMetadataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, linkShareMetadataMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.linkShareMetadataMendixObject = linkShareMetadataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'LinkShareMetadata.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static googledriveconnector.proxies.LinkShareMetadata initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return googledriveconnector.proxies.LinkShareMetadata.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static googledriveconnector.proxies.LinkShareMetadata initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new googledriveconnector.proxies.LinkShareMetadata(context, mendixObject);
	}

	public static googledriveconnector.proxies.LinkShareMetadata load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return googledriveconnector.proxies.LinkShareMetadata.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SecurityUpdateEligible
	 */
	public final java.lang.Boolean getSecurityUpdateEligible()
	{
		return getSecurityUpdateEligible(getContext());
	}

	/**
	 * @param context
	 * @return value of SecurityUpdateEligible
	 */
	public final java.lang.Boolean getSecurityUpdateEligible(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SecurityUpdateEligible.toString());
	}

	/**
	 * Set value of SecurityUpdateEligible
	 * @param securityupdateeligible
	 */
	public final void setSecurityUpdateEligible(java.lang.Boolean securityupdateeligible)
	{
		setSecurityUpdateEligible(getContext(), securityupdateeligible);
	}

	/**
	 * Set value of SecurityUpdateEligible
	 * @param context
	 * @param securityupdateeligible
	 */
	public final void setSecurityUpdateEligible(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean securityupdateeligible)
	{
		getMendixObject().setValue(context, MemberNames.SecurityUpdateEligible.toString(), securityupdateeligible);
	}

	/**
	 * @return value of SecurityUpdateEnabled
	 */
	public final java.lang.Boolean getSecurityUpdateEnabled()
	{
		return getSecurityUpdateEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of SecurityUpdateEnabled
	 */
	public final java.lang.Boolean getSecurityUpdateEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SecurityUpdateEnabled.toString());
	}

	/**
	 * Set value of SecurityUpdateEnabled
	 * @param securityupdateenabled
	 */
	public final void setSecurityUpdateEnabled(java.lang.Boolean securityupdateenabled)
	{
		setSecurityUpdateEnabled(getContext(), securityupdateenabled);
	}

	/**
	 * Set value of SecurityUpdateEnabled
	 * @param context
	 * @param securityupdateenabled
	 */
	public final void setSecurityUpdateEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean securityupdateenabled)
	{
		getMendixObject().setValue(context, MemberNames.SecurityUpdateEnabled.toString(), securityupdateenabled);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of LinkShareMetadata_GoogleDriveFile
	 */
	public final googledriveconnector.proxies.GoogleDriveFile getLinkShareMetadata_GoogleDriveFile() throws com.mendix.core.CoreException
	{
		return getLinkShareMetadata_GoogleDriveFile(getContext());
	}

	/**
	 * @param context
	 * @return value of LinkShareMetadata_GoogleDriveFile
	 * @throws com.mendix.core.CoreException
	 */
	public final googledriveconnector.proxies.GoogleDriveFile getLinkShareMetadata_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googledriveconnector.proxies.GoogleDriveFile result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.LinkShareMetadata_GoogleDriveFile.toString());
		if (identifier != null) {
			result = googledriveconnector.proxies.GoogleDriveFile.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of LinkShareMetadata_GoogleDriveFile
	 * @param linksharemetadata_googledrivefile
	 */
	public final void setLinkShareMetadata_GoogleDriveFile(googledriveconnector.proxies.GoogleDriveFile linksharemetadata_googledrivefile)
	{
		setLinkShareMetadata_GoogleDriveFile(getContext(), linksharemetadata_googledrivefile);
	}

	/**
	 * Set value of LinkShareMetadata_GoogleDriveFile
	 * @param context
	 * @param linksharemetadata_googledrivefile
	 */
	public final void setLinkShareMetadata_GoogleDriveFile(com.mendix.systemwideinterfaces.core.IContext context, googledriveconnector.proxies.GoogleDriveFile linksharemetadata_googledrivefile)
	{
		if (linksharemetadata_googledrivefile == null) {
			getMendixObject().setValue(context, MemberNames.LinkShareMetadata_GoogleDriveFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.LinkShareMetadata_GoogleDriveFile.toString(), linksharemetadata_googledrivefile.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return linkShareMetadataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final googledriveconnector.proxies.LinkShareMetadata that = (googledriveconnector.proxies.LinkShareMetadata) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
